import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  tr: {
    // Navbar
    nav: ["Anasayfa", "Hakkımızda", "Hizmetlerimiz", "Operasyonlar", "Bize Ulaşın"],
    freeConsult: "Ücretsiz Konsültasyon",
    // Hero
    heroBadge: "İstanbul, Türkiye — Premium Diş Kliniği",
    heroTitle1: "Hayalinizdeki",
    heroTitleHighlight: "Gülüşe",
    heroTitle2: "Kavuşun",
    heroDesc: "Hollywood gülüşü, diş implantları ve kozmetik diş tedavileri ile özgüveninizi yeniden keşfedin. Havalimanı transferinden kliniğe, VIP bir deneyim yaşayın.",
    heroCta: "Diş Tedavileri",
    marquee: ["🦷 Hollywood Gülüşü — Mükemmel Sonuçlar", "✨ Diş İmplantları ile Kalıcı Çözümler", "💎 Zirkonyum Kaplama Uzmanları", "🪥 Diş Beyazlatma Tedavileri", "📞 7/24 Ücretsiz Danışmanlık Hattı"],
    // Services
    servicesLabel: "Tedavilerimiz",
    servicesTitle: "Diş Tedavi Hizmetlerimiz",
    servicesDesc: "Kapsamlı diş sağlığı hizmetlerimizle ağız sağlığınızı ve estetik gülüşünüzü güvence altına alın.",
    exploreBtn: "Detaylı İncele →",
    services: [
      { title: "Diş İmplantı", desc: "Eksik dişleriniz için All-on-4 ve All-on-6 sistemleriyle kalıcı çözümler." },
      { title: "Hollywood Gülüşü", desc: "Porselen laminate ve zirkonyum kaplama ile kusursuz diş tasarımı." },
      { title: "Diş Beyazlatma", desc: "Laser beyazlatma ile profesyonel ve hızlı sonuçlar." },
      { title: "Zirkonyum Kaplama", desc: "Estetik ve dayanıklı zirkonyum kaplama ile doğal görünüm." },
      { title: "Kemik Grefti", desc: "Diş implantı için kemik yenileme ve sinus lifting işlemleri." },
      { title: "Diş Teli & Ortodonti", desc: "Şeffaf plak ve metal tel ile estetik diş hizalama tedavileri." },
    ],
    // Stats
    stats: ["Yıllık Diş Deneyimi", "Başarılı İmplant", "Hollywood Gülüşü", "Hasta Memnuniyeti"],
    // Before After
    beforeAfterBadge: "Gerçek Hasta Sonuçları",
    beforeAfterTitle: "Before & After",
    beforeAfterHighlight: "Dönüşümler",
    beforeAfterDesc: "Panorama Dental'de tedavi gören gerçek hastalarımızın inanılmaz dönüşümlerini keşfedin. Her görsel, ekibimizin mükemmellik taahhüdünü yansıtmaktadır.",
    trustBar: ["Mutlu Hasta", "Memnuniyet", "Yıl Deneyim", "Ülkeden Hasta"],
    caseLabel: "Vaka",
    ctaBadge: "Hayalinizdeki Gülüş",
    ctaTitle: "Siz de bu dönüşümü yaşayın",
    ctaDesc: "Ücretsiz konsültasyon randevunuzu alın, uzmanlarımız sizin için en uygun tedaviyi belirlesin.",
    ctaBtn: "Ücretsiz Konsültasyon",
    whatsappBtn: "WhatsApp",
    // Doctors
    doctorsLabel: "Uzmanlarımız",
    doctorsTitle: "Diş Hekimlerimizle Tanışın",
    doctorsDesc: "Tercih ettiğiniz doktoru seçin ve birkaç dakika içinde randevu alın.",
    appointmentBtn: "Randevu Al",
    doctors: [
      { specialty: "Estetik Diş Hekimi & İmplantoloji Uzmanı", exp: "12 yıl deneyim" },
      { specialty: "Ortodonti Uzmanı", exp: "8 yıl deneyim" },
      { specialty: "Periodontoloji & Diş Eti Uzmanı", exp: "10 yıl deneyim" },
    ],
    // Why Us
    whyLabel: "Neden Biz?",
    whyTitle: "Neden Panorama Dental'i Tercih Etmelisiniz?",
    whyDesc: "Diş tedavinizde doğru klinik seçimi hayat değiştiren bir karardır. Panorama Dental olarak mükemmel diş sağlığı ve estetik için en iyi deneyimi sunuyoruz.",
    reasons: [
      { title: "Uzman Diş Hekimleri", desc: "Alanında uzmanlaşmış, uluslararası sertifikalı diş hekimlerimiz her prosedürde yılların deneyimini sunar." },
      { title: "Son Teknoloji Ekipman", desc: "3D tomografi, dijital gülüş tasarımı ve laser sistemleriyle en hassas tedavileri gerçekleştiriyoruz." },
      { title: "Steril & Güvenli Ortam", desc: "Uluslararası standartlarda sterilizasyon ve hasta güvenliği protokolleriyle en hijyenik ortamı sunuyoruz." },
      { title: "Hızlı & Konforlu Tedavi", desc: "Tek seansta büyük dönüşümler mümkün. Tedavi sürecinizi mümkün olan en konforlu şekilde tamamlıyoruz." },
    ],
    // Packages
    packagesLabel: "VIP HIZMETLER",
    packagesTitle: "Sizin İçin Düşündük",
    packages: [
      { title: "Havaalanı Transferi", desc: "Havaalanından Panorama Dental'e stressiz bir transfer deneyimi yaşayın. Profesyonel şoförlerimiz sizi terminalde karşılayacak." },
      { title: "Otel Konaklama", desc: "İhtiyaçlarınıza uygun çeşitli olanaklar sunan yakındaki birçok otelle ortaklığımız var." },
      { title: "7/24 Ulaşım", desc: "Ulaşım hizmetlerimiz programınıza uyacak şekilde 7/24 hizmetinizdedir ve zamanında varış ve kalkışları garanti eder." },
      { title: "Tercüman Hizmeti", desc: "Türkiye ziyaretiniz sırasında güvenebileceğiniz her dilde uzmanlaşmış tercümanlarımız mevcuttur." },
    ],
    // Departments
    deptLabel: "Bölümlerimiz",
    deptTitle: "Tüm Diş Tedavi Alanlarımız",
    deptDesc: "Panorama Dental, ağız ve diş sağlığının tüm alanlarında uzman kadrosuyla kapsamlı hizmet sunmaktadır.",
    departments: ["Diş İmplantı", "Hollywood Gülüşü", "Zirkonyum Kaplama", "Diş Beyazlatma", "Porselen Laminate", "Diş Teli & Ortodonti", "Kanal Tedavisi", "Diş Eti Tedavisi", "Kemik Grefti", "All-on-4 / All-on-6", "Çocuk Diş Hekimliği", "Ağız & Diş Bakımı"],
    // Contact
    contactLabel: "İletişim",
    contactTitle: "Ücretsiz Danışmanlık",
    contactDesc: "Sorularınızı bize sormaktan çekinmeyin. Hemen formu doldurun, sizi arayalım.",
    phone: "Telefon", email: "E-posta", address: "Adres",
    freeConsultLine: "7/24 Ücretsiz Danışmanlık",
    namePlaceholder: "Adınız Soyadınız",
    emailPlaceholder: "E-posta Adresiniz",
    phonePlaceholder: "Telefon Numaranız",
    messagePlaceholder: "Mesajınız...",
    sendBtn: "Gönder",
    whatsappText: "Merhaba, ben",
  },
  en: {
    nav: ["Home", "About Us", "Services", "Operations", "Contact Us"],
    freeConsult: "Free Consultation",
    heroBadge: "Istanbul, Turkey — Premium Dental Clinic",
    heroTitle1: "Achieve Your",
    heroTitleHighlight: "Dream Smile",
    heroTitle2: "",
    heroDesc: "Rediscover your confidence with Hollywood smile, dental implants and cosmetic dental treatments. A VIP experience from airport transfer to the clinic.",
    heroCta: "Dental Treatments",
    marquee: ["🦷 Hollywood Smile — Perfect Results", "✨ Permanent Solutions with Dental Implants", "💎 Zirconia Crown Specialists", "🪥 Teeth Whitening Treatments", "📞 24/7 Free Consultation Line"],
    servicesLabel: "Our Treatments",
    servicesTitle: "Dental Treatment Services",
    servicesDesc: "Ensure your oral health and aesthetic smile with our comprehensive dental health services.",
    exploreBtn: "Explore →",
    services: [
      { title: "Dental Implant", desc: "Permanent solutions for missing teeth with All-on-4 and All-on-6 systems." },
      { title: "Hollywood Smile", desc: "Perfect smile design with porcelain laminates and zirconia crowns." },
      { title: "Teeth Whitening", desc: "Professional and fast results with laser whitening." },
      { title: "Zirconia Crown", desc: "Natural appearance with aesthetic and durable zirconia crowns." },
      { title: "Bone Graft", desc: "Bone regeneration and sinus lifting procedures for dental implants." },
      { title: "Braces & Orthodontics", desc: "Aesthetic teeth alignment with clear aligners and metal braces." },
    ],
    stats: ["Years of Experience", "Successful Implants", "Hollywood Smiles", "Patient Satisfaction"],
    beforeAfterBadge: "Real Patient Results",
    beforeAfterTitle: "Before & After",
    beforeAfterHighlight: "Transformations",
    beforeAfterDesc: "Discover the incredible transformations of our real patients treated at Panorama Dental.",
    trustBar: ["Happy Patients", "Satisfaction", "Years Experience", "Countries"],
    caseLabel: "Case",
    ctaBadge: "Your Dream Smile",
    ctaTitle: "Experience this transformation too",
    ctaDesc: "Book your free consultation, our experts will determine the most suitable treatment for you.",
    ctaBtn: "Free Consultation",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Our Specialists",
    doctorsTitle: "Meet Our Dentists",
    doctorsDesc: "Choose your preferred doctor and get an appointment in minutes.",
    appointmentBtn: "Book Appointment",
    doctors: [
      { specialty: "Aesthetic Dentist & Implantology Specialist", exp: "12 years experience" },
      { specialty: "Orthodontics Specialist", exp: "8 years experience" },
      { specialty: "Periodontology & Gum Specialist", exp: "10 years experience" },
    ],
    whyLabel: "Why Us?",
    whyTitle: "Why Choose Panorama Dental?",
    whyDesc: "Choosing the right clinic for your dental treatment is a life-changing decision. At Panorama Dental, we offer the best experience for perfect dental health and aesthetics.",
    reasons: [
      { title: "Expert Dentists", desc: "Our internationally certified, specialized dentists bring years of experience to every procedure." },
      { title: "Latest Technology", desc: "We perform the most precise treatments with 3D tomography, digital smile design and laser systems." },
      { title: "Sterile & Safe Environment", desc: "We provide the most hygienic environment with international sterilization and patient safety protocols." },
      { title: "Fast & Comfortable Treatment", desc: "Major transformations possible in a single session. We complete your treatment process as comfortably as possible." },
    ],
    packagesLabel: "VIP SERVICES",
    packagesTitle: "We Thought of You",
    packages: [
      { title: "Airport Transfer", desc: "Enjoy a stress-free transfer from the airport to Panorama Dental. Our professional drivers will meet you at the terminal." },
      { title: "Hotel Accommodation", desc: "We have partnerships with nearby hotels offering a variety of options to suit your needs." },
      { title: "24/7 Transportation", desc: "Our transportation services are available 24/7 to fit your schedule and guarantee timely arrivals and departures." },
      { title: "Interpreter Service", desc: "We have specialized interpreters in every language you can rely on during your visit to Turkey." },
    ],
    deptLabel: "Our Departments",
    deptTitle: "All Dental Treatment Areas",
    deptDesc: "Panorama Dental provides comprehensive services in all areas of oral and dental health with an expert team.",
    departments: ["Dental Implant", "Hollywood Smile", "Zirconia Crown", "Teeth Whitening", "Porcelain Laminate", "Braces & Orthodontics", "Root Canal", "Gum Treatment", "Bone Graft", "All-on-4 / All-on-6", "Pediatric Dentistry", "Oral & Dental Care"],
    contactLabel: "Contact",
    contactTitle: "Free Consultation",
    contactDesc: "Don't hesitate to ask us your questions. Fill in the form now, we'll call you.",
    phone: "Phone", email: "Email", address: "Address",
    freeConsultLine: "24/7 Free Consultation",
    namePlaceholder: "Your Full Name",
    emailPlaceholder: "Your Email Address",
    phonePlaceholder: "Your Phone Number",
    messagePlaceholder: "Your Message...",
    sendBtn: "Send",
    whatsappText: "Hello, I am",
  },
  de: {
    nav: ["Startseite", "Über Uns", "Leistungen", "Operationen", "Kontakt"],
    freeConsult: "Kostenlose Beratung",
    heroBadge: "Istanbul, Türkei — Premium Zahnklinik",
    heroTitle1: "Ihr Traum-",
    heroTitleHighlight: "Lächeln",
    heroTitle2: "Verwirklichen",
    heroDesc: "Entdecken Sie Ihr Selbstvertrauen mit Hollywood-Lächeln, Zahnimplantaten und kosmetischen Zahnbehandlungen. Ein VIP-Erlebnis vom Flughafentransfer bis zur Klinik.",
    heroCta: "Zahnbehandlungen",
    marquee: ["🦷 Hollywood-Lächeln — Perfekte Ergebnisse", "✨ Dauerhafte Lösungen mit Zahnimplantaten", "💎 Zirkon-Spezialisten", "🪥 Zahnaufhellung", "📞 24/7 Kostenlose Beratung"],
    servicesLabel: "Unsere Behandlungen",
    servicesTitle: "Zahnmedizinische Leistungen",
    servicesDesc: "Sichern Sie Ihre Mundgesundheit und Ihr ästhetisches Lächeln mit unseren umfassenden Dienstleistungen.",
    exploreBtn: "Mehr erfahren →",
    services: [
      { title: "Zahnimplantat", desc: "Dauerhafte Lösungen für fehlende Zähne mit All-on-4 und All-on-6 Systemen." },
      { title: "Hollywood-Lächeln", desc: "Perfektes Lächeln-Design mit Porzellanschalen und Zirkonkronen." },
      { title: "Zahnaufhellung", desc: "Professionelle und schnelle Ergebnisse mit Laser-Bleaching." },
      { title: "Zirkonkrone", desc: "Natürliches Aussehen mit ästhetischen und haltbaren Zirkonkronen." },
      { title: "Knochentransplantat", desc: "Knochenregeneration und Sinuslift für Zahnimplantate." },
      { title: "Zahnspange & Kieferorthopädie", desc: "Ästhetische Zahnkorrektur mit transparenten und Metallspangen." },
    ],
    stats: ["Jahre Erfahrung", "Erfolgreiche Implantate", "Hollywood-Lächeln", "Patientenzufriedenheit"],
    beforeAfterBadge: "Echte Patientenergebnisse",
    beforeAfterTitle: "Vorher & Nachher",
    beforeAfterHighlight: "Transformationen",
    beforeAfterDesc: "Entdecken Sie die unglaublichen Transformationen unserer echten Patienten in Panorama Dental.",
    trustBar: ["Zufriedene Patienten", "Zufriedenheit", "Jahre Erfahrung", "Länder"],
    caseLabel: "Fall",
    ctaBadge: "Ihr Traumlächeln",
    ctaTitle: "Erleben Sie auch diese Transformation",
    ctaDesc: "Buchen Sie Ihre kostenlose Beratung, unsere Experten bestimmen die geeignetste Behandlung für Sie.",
    ctaBtn: "Kostenlose Beratung",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Unsere Spezialisten",
    doctorsTitle: "Lernen Sie unsere Zahnärzte kennen",
    doctorsDesc: "Wählen Sie Ihren bevorzugten Arzt und vereinbaren Sie in wenigen Minuten einen Termin.",
    appointmentBtn: "Termin buchen",
    doctors: [
      { specialty: "Ästhetische Zahnärztin & Implantologie-Spezialistin", exp: "12 Jahre Erfahrung" },
      { specialty: "Kieferorthopädie-Spezialist", exp: "8 Jahre Erfahrung" },
      { specialty: "Parodontologie & Zahnfleisch-Spezialistin", exp: "10 Jahre Erfahrung" },
    ],
    whyLabel: "Warum wir?",
    whyTitle: "Warum Panorama Dental wählen?",
    whyDesc: "Die Wahl der richtigen Klinik für Ihre Zahnbehandlung ist eine lebensverändernde Entscheidung.",
    reasons: [
      { title: "Experten-Zahnärzte", desc: "Unsere international zertifizierten Zahnärzte bringen jahrelange Erfahrung bei jedem Eingriff mit." },
      { title: "Neueste Technologie", desc: "Wir führen die präzisesten Behandlungen mit 3D-Tomographie und Lasersystemen durch." },
      { title: "Sterile & Sichere Umgebung", desc: "Wir bieten die hygienischste Umgebung mit internationalen Sterilisationsprotokollen." },
      { title: "Schnelle & Komfortable Behandlung", desc: "Große Transformationen in einer einzigen Sitzung möglich." },
    ],
    packagesLabel: "VIP SERVICES",
    packagesTitle: "Wir haben an Sie gedacht",
    packages: [
      { title: "Flughafentransfer", desc: "Genießen Sie einen stressfreien Transfer vom Flughafen zu Panorama Dental." },
      { title: "Hotelunterkunft", desc: "Wir haben Partnerschaften mit nahe gelegenen Hotels, die verschiedene Optionen bieten." },
      { title: "24/7 Transport", desc: "Unsere Transportdienste sind rund um die Uhr verfügbar." },
      { title: "Dolmetscherdienst", desc: "Wir haben spezialisierte Dolmetscher in jeder Sprache für Ihren Türkei-Besuch." },
    ],
    deptLabel: "Unsere Abteilungen",
    deptTitle: "Alle Zahnbehandlungsbereiche",
    deptDesc: "Panorama Dental bietet umfassende Dienstleistungen in allen Bereichen der Mund- und Zahngesundheit.",
    departments: ["Zahnimplantat", "Hollywood-Lächeln", "Zirkonkrone", "Zahnaufhellung", "Porzellanfacette", "Zahnspange & Kieferorthopädie", "Wurzelkanal", "Zahnfleischbehandlung", "Knochentransplantat", "All-on-4 / All-on-6", "Kinderzahnheilkunde", "Mund- & Zahnpflege"],
    contactLabel: "Kontakt",
    contactTitle: "Kostenlose Beratung",
    contactDesc: "Stellen Sie uns Ihre Fragen. Füllen Sie das Formular aus, wir rufen Sie zurück.",
    phone: "Telefon", email: "E-Mail", address: "Adresse",
    freeConsultLine: "24/7 Kostenlose Beratung",
    namePlaceholder: "Ihr vollständiger Name",
    emailPlaceholder: "Ihre E-Mail-Adresse",
    phonePlaceholder: "Ihre Telefonnummer",
    messagePlaceholder: "Ihre Nachricht...",
    sendBtn: "Senden",
    whatsappText: "Hallo, ich bin",
  },
  ar: {
    nav: ["الرئيسية", "من نحن", "خدماتنا", "العمليات", "اتصل بنا"],
    freeConsult: "استشارة مجانية",
    heroBadge: "إسطنبول، تركيا — عيادة أسنان متميزة",
    heroTitle1: "احصل على",
    heroTitleHighlight: "ابتسامة أحلامك",
    heroTitle2: "",
    heroDesc: "أعد اكتشاف ثقتك بنفسك مع ابتسامة هوليوود وزراعة الأسنان وعلاجات الأسنان التجميلية. تجربة VIP من المطار إلى العيادة.",
    heroCta: "علاجات الأسنان",
    marquee: ["🦷 ابتسامة هوليوود — نتائج مثالية", "✨ حلول دائمة بزراعة الأسنان", "💎 متخصصون في تيجان الزركونيا", "🪥 علاجات تبييض الأسنان", "📞 خط استشارة مجاني 24/7"],
    servicesLabel: "علاجاتنا",
    servicesTitle: "خدمات علاج الأسنان",
    servicesDesc: "حافظ على صحة فمك وابتسامتك الجمالية من خلال خدماتنا الشاملة لصحة الأسنان.",
    exploreBtn: "استكشف →",
    services: [
      { title: "زراعة الأسنان", desc: "حلول دائمة للأسنان المفقودة بأنظمة All-on-4 وAll-on-6." },
      { title: "ابتسامة هوليوود", desc: "تصميم ابتسامة مثالية بالقشور الخزفية وتيجان الزركونيا." },
      { title: "تبييض الأسنان", desc: "نتائج احترافية وسريعة بتبييض الليزر." },
      { title: "تاج الزركونيا", desc: "مظهر طبيعي بتيجان الزركونيا الجمالية والمتينة." },
      { title: "زراعة العظام", desc: "تجديد العظام ورفع الجيب الأنفي لزراعة الأسنان." },
      { title: "تقويم الأسنان", desc: "محاذاة الأسنان الجمالية بمحاذيات شفافة وتقويم معدني." },
    ],
    stats: ["سنوات خبرة", "زرعة ناجحة", "ابتسامة هوليوود", "رضا المرضى"],
    beforeAfterBadge: "نتائج مرضى حقيقيين",
    beforeAfterTitle: "قبل وبعد",
    beforeAfterHighlight: "التحولات",
    beforeAfterDesc: "اكتشف التحولات المذهلة لمرضانا الحقيقيين الذين عولجوا في باناروما دنتال.",
    trustBar: ["مريض سعيد", "رضا", "سنوات خبرة", "دولة"],
    caseLabel: "حالة",
    ctaBadge: "ابتسامة أحلامك",
    ctaTitle: "عش هذا التحول أنت أيضاً",
    ctaDesc: "احجز استشارتك المجانية، سيحدد خبراؤنا العلاج الأنسب لك.",
    ctaBtn: "استشارة مجانية",
    whatsappBtn: "واتساب",
    doctorsLabel: "متخصصونا",
    doctorsTitle: "تعرف على أطبائنا",
    doctorsDesc: "اختر طبيبك المفضل واحصل على موعد في دقائق.",
    appointmentBtn: "احجز موعداً",
    doctors: [
      { specialty: "طبيبة أسنان تجميلية ومتخصصة في زراعة الأسنان", exp: "12 سنة خبرة" },
      { specialty: "متخصص في تقويم الأسنان", exp: "8 سنوات خبرة" },
      { specialty: "متخصصة في أمراض اللثة", exp: "10 سنوات خبرة" },
    ],
    whyLabel: "لماذا نحن؟",
    whyTitle: "لماذا تختار باناروما دنتال؟",
    whyDesc: "اختيار العيادة الصحيحة لعلاج أسنانك قرار يغير الحياة.",
    reasons: [
      { title: "أطباء متخصصون", desc: "أطباؤنا المعتمدون دولياً يجلبون سنوات من الخبرة لكل إجراء." },
      { title: "أحدث التقنيات", desc: "نجري أدق العلاجات بالتصوير المقطعي ثلاثي الأبعاد وأنظمة الليزر." },
      { title: "بيئة معقمة وآمنة", desc: "نوفر أكثر البيئات نظافة وفق بروتوكولات التعقيم الدولية." },
      { title: "علاج سريع ومريح", desc: "تحولات كبيرة ممكنة في جلسة واحدة." },
    ],
    packagesLabel: "خدمات VIP",
    packagesTitle: "فكرنا فيك",
    packages: [
      { title: "نقل المطار", desc: "استمتع بنقل خالٍ من التوتر من المطار إلى باناروما دنتال." },
      { title: "إقامة فندقية", desc: "لدينا شراكات مع فنادق قريبة تقدم خيارات متنوعة." },
      { title: "نقل 24/7", desc: "خدمات النقل لدينا متاحة على مدار الساعة." },
      { title: "خدمة الترجمة", desc: "لدينا مترجمون متخصصون بكل اللغات لزيارتك لتركيا." },
    ],
    deptLabel: "أقسامنا",
    deptTitle: "جميع مجالات علاج الأسنان",
    deptDesc: "تقدم باناروما دنتال خدمات شاملة في جميع مجالات صحة الفم والأسنان.",
    departments: ["زراعة الأسنان", "ابتسامة هوليوود", "تاج الزركونيا", "تبييض الأسنان", "قشور البورسلين", "تقويم الأسنان", "علاج الجذور", "علاج اللثة", "زراعة العظام", "All-on-4 / All-on-6", "طب أسنان الأطفال", "العناية بالفم والأسنان"],
    contactLabel: "التواصل",
    contactTitle: "استشارة مجانية",
    contactDesc: "لا تتردد في طرح أسئلتك. املأ النموذج الآن وسنتصل بك.",
    phone: "الهاتف", email: "البريد الإلكتروني", address: "العنوان",
    freeConsultLine: "استشارة مجانية 24/7",
    namePlaceholder: "اسمك الكامل",
    emailPlaceholder: "بريدك الإلكتروني",
    phonePlaceholder: "رقم هاتفك",
    messagePlaceholder: "رسالتك...",
    sendBtn: "إرسال",
    whatsappText: "مرحباً، أنا",
  },
  es: {
    nav: ["Inicio", "Sobre Nosotros", "Servicios", "Operaciones", "Contáctenos"],
    freeConsult: "Consulta Gratuita",
    heroBadge: "Estambul, Turquía — Clínica Dental Premium",
    heroTitle1: "Consiga su",
    heroTitleHighlight: "Sonrisa Soñada",
    heroTitle2: "",
    heroDesc: "Redescubra su confianza con sonrisa Hollywood, implantes dentales y tratamientos cosméticos. Una experiencia VIP desde el aeropuerto hasta la clínica.",
    heroCta: "Tratamientos Dentales",
    marquee: ["🦷 Sonrisa Hollywood — Resultados Perfectos", "✨ Soluciones Permanentes con Implantes Dentales", "💎 Especialistas en Coronas de Zirconio", "🪥 Tratamientos de Blanqueamiento", "📞 Línea de Consulta Gratuita 24/7"],
    servicesLabel: "Nuestros Tratamientos",
    servicesTitle: "Servicios de Tratamiento Dental",
    servicesDesc: "Asegure su salud bucal y sonrisa estética con nuestros servicios integrales de salud dental.",
    exploreBtn: "Explorar →",
    services: [
      { title: "Implante Dental", desc: "Soluciones permanentes para dientes perdidos con sistemas All-on-4 y All-on-6." },
      { title: "Sonrisa Hollywood", desc: "Diseño de sonrisa perfecto con carillas de porcelana y coronas de zirconio." },
      { title: "Blanqueamiento Dental", desc: "Resultados profesionales y rápidos con blanqueamiento láser." },
      { title: "Corona de Zirconio", desc: "Apariencia natural con coronas de zirconio estéticas y duraderas." },
      { title: "Injerto Óseo", desc: "Regeneración ósea y elevación de seno para implantes dentales." },
      { title: "Ortodoncia", desc: "Alineación dental estética con alineadores transparentes y brackets metálicos." },
    ],
    stats: ["Años de Experiencia", "Implantes Exitosos", "Sonrisas Hollywood", "Satisfacción del Paciente"],
    beforeAfterBadge: "Resultados de Pacientes Reales",
    beforeAfterTitle: "Antes & Después",
    beforeAfterHighlight: "Transformaciones",
    beforeAfterDesc: "Descubra las increíbles transformaciones de nuestros pacientes reales tratados en Panorama Dental.",
    trustBar: ["Pacientes Felices", "Satisfacción", "Años Experiencia", "Países"],
    caseLabel: "Caso",
    ctaBadge: "Tu Sonrisa Soñada",
    ctaTitle: "Vive también esta transformación",
    ctaDesc: "Reserve su consulta gratuita, nuestros expertos determinarán el tratamiento más adecuado para usted.",
    ctaBtn: "Consulta Gratuita",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Nuestros Especialistas",
    doctorsTitle: "Conozca a Nuestros Dentistas",
    doctorsDesc: "Elija su médico preferido y obtenga una cita en minutos.",
    appointmentBtn: "Reservar Cita",
    doctors: [
      { specialty: "Dentista Estética & Especialista en Implantología", exp: "12 años de experiencia" },
      { specialty: "Especialista en Ortodoncia", exp: "8 años de experiencia" },
      { specialty: "Especialista en Periodoncia & Encías", exp: "10 años de experiencia" },
    ],
    whyLabel: "¿Por Qué Nosotros?",
    whyTitle: "¿Por Qué Elegir Panorama Dental?",
    whyDesc: "Elegir la clínica correcta para su tratamiento dental es una decisión que cambia la vida.",
    reasons: [
      { title: "Dentistas Expertos", desc: "Nuestros dentistas certificados internacionalmente aportan años de experiencia a cada procedimiento." },
      { title: "Última Tecnología", desc: "Realizamos los tratamientos más precisos con tomografía 3D y sistemas láser." },
      { title: "Entorno Estéril y Seguro", desc: "Ofrecemos el entorno más higiénico con protocolos de esterilización internacionales." },
      { title: "Tratamiento Rápido y Cómodo", desc: "Grandes transformaciones posibles en una sola sesión." },
    ],
    packagesLabel: "SERVICIOS VIP",
    packagesTitle: "Pensamos en Usted",
    packages: [
      { title: "Traslado al Aeropuerto", desc: "Disfrute de un traslado sin estrés desde el aeropuerto a Panorama Dental." },
      { title: "Alojamiento en Hotel", desc: "Tenemos asociaciones con hoteles cercanos que ofrecen diversas opciones." },
      { title: "Transporte 24/7", desc: "Nuestros servicios de transporte están disponibles las 24 horas." },
      { title: "Servicio de Intérprete", desc: "Tenemos intérpretes especializados en todos los idiomas para su visita a Turquía." },
    ],
    deptLabel: "Nuestros Departamentos",
    deptTitle: "Todas las Áreas de Tratamiento Dental",
    deptDesc: "Panorama Dental ofrece servicios integrales en todas las áreas de la salud bucal y dental.",
    departments: ["Implante Dental", "Sonrisa Hollywood", "Corona de Zirconio", "Blanqueamiento Dental", "Carilla de Porcelana", "Ortodoncia", "Endodoncia", "Tratamiento de Encías", "Injerto Óseo", "All-on-4 / All-on-6", "Odontopediatría", "Cuidado Oral"],
    contactLabel: "Contacto",
    contactTitle: "Consulta Gratuita",
    contactDesc: "No dude en hacernos sus preguntas. Rellene el formulario, le llamaremos.",
    phone: "Teléfono", email: "Correo Electrónico", address: "Dirección",
    freeConsultLine: "Consulta Gratuita 24/7",
    namePlaceholder: "Su Nombre Completo",
    emailPlaceholder: "Su Correo Electrónico",
    phonePlaceholder: "Su Número de Teléfono",
    messagePlaceholder: "Su Mensaje...",
    sendBtn: "Enviar",
    whatsappText: "Hola, soy",
  },
  it: {
    nav: ["Home", "Chi Siamo", "Servizi", "Operazioni", "Contattaci"],
    freeConsult: "Consulenza Gratuita",
    heroBadge: "Istanbul, Turchia — Clinica Dentale Premium",
    heroTitle1: "Ottieni il tuo",
    heroTitleHighlight: "Sorriso dei Sogni",
    heroTitle2: "",
    heroDesc: "Riscopri la tua fiducia con il sorriso Hollywood, gli impianti dentali e i trattamenti estetici. Un'esperienza VIP dal trasferimento aeroportuale alla clinica.",
    heroCta: "Trattamenti Dentali",
    marquee: ["🦷 Sorriso Hollywood — Risultati Perfetti", "✨ Soluzioni Permanenti con Impianti Dentali", "💎 Specialisti in Corone in Zirconio", "🪥 Trattamenti Sbiancamento", "📞 Linea di Consulenza Gratuita 24/7"],
    servicesLabel: "I Nostri Trattamenti",
    servicesTitle: "Servizi di Cura Dentale",
    servicesDesc: "Garantisci la tua salute orale e il tuo sorriso estetico con i nostri servizi dentali completi.",
    exploreBtn: "Scopri →",
    services: [
      { title: "Impianto Dentale", desc: "Soluzioni permanenti per denti mancanti con sistemi All-on-4 e All-on-6." },
      { title: "Sorriso Hollywood", desc: "Design del sorriso perfetto con faccette in porcellana e corone in zirconio." },
      { title: "Sbiancamento Dentale", desc: "Risultati professionali e veloci con sbiancamento laser." },
      { title: "Corona in Zirconio", desc: "Aspetto naturale con corone in zirconio estetiche e durature." },
      { title: "Innesto Osseo", desc: "Rigenerazione ossea e rialzo del seno per impianti dentali." },
      { title: "Ortodonzia", desc: "Allineamento dentale estetico con allineatori trasparenti e apparecchi fissi." },
    ],
    stats: ["Anni di Esperienza", "Impianti Riusciti", "Sorrisi Hollywood", "Soddisfazione Pazienti"],
    beforeAfterBadge: "Risultati Reali dei Pazienti",
    beforeAfterTitle: "Prima & Dopo",
    beforeAfterHighlight: "Trasformazioni",
    beforeAfterDesc: "Scopri le incredibili trasformazioni dei nostri veri pazienti trattati a Panorama Dental.",
    trustBar: ["Pazienti Felici", "Soddisfazione", "Anni Esperienza", "Paesi"],
    caseLabel: "Caso",
    ctaBadge: "Il Tuo Sorriso dei Sogni",
    ctaTitle: "Vivi anche tu questa trasformazione",
    ctaDesc: "Prenota la tua consulenza gratuita, i nostri esperti determineranno il trattamento più adatto per te.",
    ctaBtn: "Consulenza Gratuita",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "I Nostri Specialisti",
    doctorsTitle: "Incontra i Nostri Dentisti",
    doctorsDesc: "Scegli il tuo medico preferito e prenota un appuntamento in pochi minuti.",
    appointmentBtn: "Prenota Appuntamento",
    doctors: [
      { specialty: "Dentista Estetica & Specialista Implantologia", exp: "12 anni di esperienza" },
      { specialty: "Specialista Ortodonzia", exp: "8 anni di esperienza" },
      { specialty: "Specialista Parodontologia & Gengive", exp: "10 anni di esperienza" },
    ],
    whyLabel: "Perché Noi?",
    whyTitle: "Perché Scegliere Panorama Dental?",
    whyDesc: "Scegliere la clinica giusta per il trattamento dentale è una decisione che cambia la vita.",
    reasons: [
      { title: "Dentisti Esperti", desc: "I nostri dentisti certificati internazionalmente portano anni di esperienza ad ogni procedura." },
      { title: "Ultima Tecnologia", desc: "Eseguiamo i trattamenti più precisi con tomografia 3D e sistemi laser." },
      { title: "Ambiente Sterile e Sicuro", desc: "Offriamo l'ambiente più igienico con protocolli di sterilizzazione internazionali." },
      { title: "Trattamento Rapido e Confortevole", desc: "Grandi trasformazioni possibili in una singola sessione." },
    ],
    packagesLabel: "SERVIZI VIP",
    packagesTitle: "Abbiamo Pensato a Te",
    packages: [
      { title: "Trasferimento Aeroportuale", desc: "Goditi un trasferimento senza stress dall'aeroporto a Panorama Dental." },
      { title: "Alloggio in Hotel", desc: "Abbiamo partnership con hotel vicini che offrono varie opzioni." },
      { title: "Trasporto 24/7", desc: "I nostri servizi di trasporto sono disponibili 24 ore su 24." },
      { title: "Servizio Interprete", desc: "Abbiamo interpreti specializzati in tutte le lingue per la tua visita in Turchia." },
    ],
    deptLabel: "I Nostri Reparti",
    deptTitle: "Tutte le Aree di Trattamento Dentale",
    deptDesc: "Panorama Dental offre servizi completi in tutte le aree della salute orale e dentale.",
    departments: ["Impianto Dentale", "Sorriso Hollywood", "Corona in Zirconio", "Sbiancamento Dentale", "Faccetta in Porcellana", "Ortodonzia", "Endodonzia", "Cura delle Gengive", "Innesto Osseo", "All-on-4 / All-on-6", "Odontoiatria Pediatrica", "Igiene Orale"],
    contactLabel: "Contatto",
    contactTitle: "Consulenza Gratuita",
    contactDesc: "Non esitare a farci le tue domande. Compila il modulo, ti richiameremo.",
    phone: "Telefono", email: "Email", address: "Indirizzo",
    freeConsultLine: "Consulenza Gratuita 24/7",
    namePlaceholder: "Il Tuo Nome Completo",
    emailPlaceholder: "Il Tuo Indirizzo Email",
    phonePlaceholder: "Il Tuo Numero di Telefono",
    messagePlaceholder: "Il Tuo Messaggio...",
    sendBtn: "Invia",
    whatsappText: "Ciao, sono",
  },
  fr: {
    nav: ["Accueil", "À Propos", "Services", "Opérations", "Contactez-Nous"],
    freeConsult: "Consultation Gratuite",
    heroBadge: "Istanbul, Turquie — Clinique Dentaire Premium",
    heroTitle1: "Obtenez votre",
    heroTitleHighlight: "Sourire de Rêve",
    heroTitle2: "",
    heroDesc: "Retrouvez confiance en vous avec le sourire Hollywood, les implants dentaires et les traitements cosmétiques. Une expérience VIP du transfert aéroport à la clinique.",
    heroCta: "Traitements Dentaires",
    marquee: ["🦷 Sourire Hollywood — Résultats Parfaits", "✨ Solutions Permanentes avec Implants Dentaires", "💎 Spécialistes Couronnes Zircone", "🪥 Traitements Blanchiment", "📞 Ligne Consultation Gratuite 24/7"],
    servicesLabel: "Nos Traitements",
    servicesTitle: "Services de Soins Dentaires",
    servicesDesc: "Assurez votre santé bucco-dentaire et votre sourire esthétique avec nos services dentaires complets.",
    exploreBtn: "Explorer →",
    services: [
      { title: "Implant Dentaire", desc: "Solutions permanentes pour les dents manquantes avec les systèmes All-on-4 et All-on-6." },
      { title: "Sourire Hollywood", desc: "Design parfait du sourire avec des facettes en porcelaine et des couronnes en zircone." },
      { title: "Blanchiment Dentaire", desc: "Résultats professionnels et rapides avec le blanchiment au laser." },
      { title: "Couronne en Zircone", desc: "Aspect naturel avec des couronnes en zircone esthétiques et durables." },
      { title: "Greffe Osseuse", desc: "Régénération osseuse et élévation du sinus pour les implants dentaires." },
      { title: "Orthodontie", desc: "Alignement dentaire esthétique avec des aligneurs transparents et des appareils." },
    ],
    stats: ["Années d'Expérience", "Implants Réussis", "Sourires Hollywood", "Satisfaction Patients"],
    beforeAfterBadge: "Vrais Résultats de Patients",
    beforeAfterTitle: "Avant & Après",
    beforeAfterHighlight: "Transformations",
    beforeAfterDesc: "Découvrez les incroyables transformations de nos vrais patients traités à Panorama Dental.",
    trustBar: ["Patients Heureux", "Satisfaction", "Ans d'Expérience", "Pays"],
    caseLabel: "Cas",
    ctaBadge: "Votre Sourire de Rêve",
    ctaTitle: "Vivez vous aussi cette transformation",
    ctaDesc: "Réservez votre consultation gratuite, nos experts détermineront le traitement le plus adapté pour vous.",
    ctaBtn: "Consultation Gratuite",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Nos Spécialistes",
    doctorsTitle: "Rencontrez Nos Dentistes",
    doctorsDesc: "Choisissez votre médecin préféré et obtenez un rendez-vous en quelques minutes.",
    appointmentBtn: "Prendre Rendez-vous",
    doctors: [
      { specialty: "Dentiste Esthétique & Spécialiste Implantologie", exp: "12 ans d'expérience" },
      { specialty: "Spécialiste Orthodontie", exp: "8 ans d'expérience" },
      { specialty: "Spécialiste Parodontologie & Gencives", exp: "10 ans d'expérience" },
    ],
    whyLabel: "Pourquoi Nous?",
    whyTitle: "Pourquoi Choisir Panorama Dental?",
    whyDesc: "Choisir la bonne clinique pour votre traitement dentaire est une décision qui change la vie.",
    reasons: [
      { title: "Dentistes Experts", desc: "Nos dentistes certifiés internationalement apportent des années d'expérience à chaque procédure." },
      { title: "Dernière Technologie", desc: "Nous effectuons les traitements les plus précis avec tomographie 3D et systèmes laser." },
      { title: "Environnement Stérile et Sûr", desc: "Nous offrons l'environnement le plus hygiénique avec des protocoles de stérilisation internationaux." },
      { title: "Traitement Rapide et Confortable", desc: "Grandes transformations possibles en une seule séance." },
    ],
    packagesLabel: "SERVICES VIP",
    packagesTitle: "Nous Avons Pensé à Vous",
    packages: [
      { title: "Transfert Aéroport", desc: "Profitez d'un transfert sans stress de l'aéroport à Panorama Dental." },
      { title: "Hébergement à l'Hôtel", desc: "Nous avons des partenariats avec des hôtels proches offrant diverses options." },
      { title: "Transport 24/7", desc: "Nos services de transport sont disponibles 24 heures sur 24." },
      { title: "Service d'Interprète", desc: "Nous avons des interprètes spécialisés dans toutes les langues pour votre visite en Turquie." },
    ],
    deptLabel: "Nos Départements",
    deptTitle: "Tous les Domaines de Traitement Dentaire",
    deptDesc: "Panorama Dental offre des services complets dans tous les domaines de la santé bucco-dentaire.",
    departments: ["Implant Dentaire", "Sourire Hollywood", "Couronne en Zircone", "Blanchiment Dentaire", "Facette en Porcelaine", "Orthodontie", "Endodontie", "Traitement des Gencives", "Greffe Osseuse", "All-on-4 / All-on-6", "Dentisterie Pédiatrique", "Hygiène Bucco-Dentaire"],
    contactLabel: "Contact",
    contactTitle: "Consultation Gratuite",
    contactDesc: "N'hésitez pas à nous poser vos questions. Remplissez le formulaire, nous vous rappellerons.",
    phone: "Téléphone", email: "E-mail", address: "Adresse",
    freeConsultLine: "Consultation Gratuite 24/7",
    namePlaceholder: "Votre Nom Complet",
    emailPlaceholder: "Votre Adresse E-mail",
    phonePlaceholder: "Votre Numéro de Téléphone",
    messagePlaceholder: "Votre Message...",
    sendBtn: "Envoyer",
    whatsappText: "Bonjour, je suis",
  },
  ru: {
    nav: ["Главная", "О Нас", "Услуги", "Операции", "Свяжитесь с Нами"],
    freeConsult: "Бесплатная Консультация",
    heroBadge: "Стамбул, Турция — Премиум Стоматологическая Клиника",
    heroTitle1: "Получите улыбку",
    heroTitleHighlight: "Вашей Мечты",
    heroTitle2: "",
    heroDesc: "Обретите уверенность с голливудской улыбкой, зубными имплантами и косметическими процедурами. VIP-опыт от трансфера из аэропорта до клиники.",
    heroCta: "Стоматологические Услуги",
    marquee: ["🦷 Голливудская Улыбка — Идеальные Результаты", "✨ Постоянные Решения с Зубными Имплантами", "💎 Специалисты по Циркониевым Коронкам", "🪥 Процедуры Отбеливания Зубов", "📞 Бесплатная Консультация 24/7"],
    servicesLabel: "Наши Услуги",
    servicesTitle: "Стоматологические Услуги",
    servicesDesc: "Обеспечьте здоровье полости рта и эстетическую улыбку с нашими комплексными стоматологическими услугами.",
    exploreBtn: "Подробнее →",
    services: [
      { title: "Зубной Имплант", desc: "Постоянные решения для отсутствующих зубов с системами All-on-4 и All-on-6." },
      { title: "Голливудская Улыбка", desc: "Идеальный дизайн улыбки с фарфоровыми винирами и циркониевыми коронками." },
      { title: "Отбеливание Зубов", desc: "Профессиональные и быстрые результаты с лазерным отбеливанием." },
      { title: "Циркониевая Коронка", desc: "Естественный вид с эстетичными и прочными циркониевыми коронками." },
      { title: "Костная Пластика", desc: "Регенерация кости и синус-лифтинг для зубных имплантов." },
      { title: "Ортодонтия", desc: "Эстетическое выравнивание зубов с прозрачными элайнерами и брекетами." },
    ],
    stats: ["Лет Опыта", "Успешных Имплантов", "Голливудских Улыбок", "Удовлетворённость Пациентов"],
    beforeAfterBadge: "Реальные Результаты Пациентов",
    beforeAfterTitle: "До & После",
    beforeAfterHighlight: "Трансформации",
    beforeAfterDesc: "Откройте для себя невероятные преобразования наших реальных пациентов в Panorama Dental.",
    trustBar: ["Довольных Пациентов", "Удовлетворённость", "Лет Опыта", "Стран"],
    caseLabel: "Случай",
    ctaBadge: "Улыбка Вашей Мечты",
    ctaTitle: "Переживите и вы это преображение",
    ctaDesc: "Запишитесь на бесплатную консультацию, наши специалисты определят наиболее подходящее лечение для вас.",
    ctaBtn: "Бесплатная Консультация",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Наши Специалисты",
    doctorsTitle: "Познакомьтесь с Нашими Стоматологами",
    doctorsDesc: "Выберите предпочтительного врача и запишитесь на приём за несколько минут.",
    appointmentBtn: "Записаться",
    doctors: [
      { specialty: "Эстетический Стоматолог & Специалист по Имплантологии", exp: "12 лет опыта" },
      { specialty: "Специалист по Ортодонтии", exp: "8 лет опыта" },
      { specialty: "Специалист по Пародонтологии & Дёснам", exp: "10 лет опыта" },
    ],
    whyLabel: "Почему Мы?",
    whyTitle: "Почему Выбирают Panorama Dental?",
    whyDesc: "Выбор правильной клиники для лечения зубов — это решение, меняющее жизнь.",
    reasons: [
      { title: "Опытные Стоматологи", desc: "Наши международно сертифицированные стоматологи привносят многолетний опыт в каждую процедуру." },
      { title: "Новейшие Технологии", desc: "Мы выполняем точнейшие процедуры с 3D-томографией и лазерными системами." },
      { title: "Стерильная и Безопасная Среда", desc: "Мы обеспечиваем максимально гигиеничную среду с международными протоколами стерилизации." },
      { title: "Быстрое и Комфортное Лечение", desc: "Большие преобразования возможны за один сеанс." },
    ],
    packagesLabel: "VIP УСЛУГИ",
    packagesTitle: "Мы Позаботились о Вас",
    packages: [
      { title: "Трансфер из Аэропорта", desc: "Наслаждайтесь трансфером без стресса от аэропорта до Panorama Dental." },
      { title: "Проживание в Отеле", desc: "У нас есть партнёрства с близлежащими отелями, предлагающими различные варианты." },
      { title: "Транспорт 24/7", desc: "Наши транспортные услуги доступны круглосуточно." },
      { title: "Услуги Переводчика", desc: "У нас есть специализированные переводчики на все языки для вашего визита в Турцию." },
    ],
    deptLabel: "Наши Отделения",
    deptTitle: "Все Области Стоматологического Лечения",
    deptDesc: "Panorama Dental предоставляет комплексные услуги во всех областях здоровья полости рта.",
    departments: ["Зубной Имплант", "Голливудская Улыбка", "Циркониевая Коронка", "Отбеливание Зубов", "Фарфоровый Винир", "Ортодонтия", "Эндодонтия", "Лечение Дёсен", "Костная Пластика", "All-on-4 / All-on-6", "Детская Стоматология", "Гигиена Полости Рта"],
    contactLabel: "Контакты",
    contactTitle: "Бесплатная Консультация",
    contactDesc: "Не стесняйтесь задавать нам вопросы. Заполните форму, мы перезвоним вам.",
    phone: "Телефон", email: "Электронная Почта", address: "Адрес",
    freeConsultLine: "Бесплатная Консультация 24/7",
    namePlaceholder: "Ваше Полное Имя",
    emailPlaceholder: "Ваш Адрес Электронной Почты",
    phonePlaceholder: "Ваш Номер Телефона",
    messagePlaceholder: "Ваше Сообщение...",
    sendBtn: "Отправить",
    whatsappText: "Здравствуйте, я",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("tr");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}