import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  tr: {
    // Navbar
    nav: ["Anasayfa", "Hakkımızda", "Hizmetlerimiz", "Operasyonlar", "Bize Ulaşın"],
    freeConsult: "Ücretsiz Konsültasyon",
    // Hero
    heroBadge: "İstanbul, Türkiye — Haliç Panorama Dental",
    heroTitle1: "Hayalinizdeki",
    heroTitleHighlight: "Gülüşe",
    heroTitle2: "Kavuşun",
    heroDesc: "Hollywood gülüşü, diş implantları ve kozmetik diş tedavileri ile özgüveninizi yeniden keşfedin. Havalimanı transferinden kliniğe, VIP bir deneyim yaşayın.",
    heroCta: "Diş Tedavileri",

    marquee: ["🦷 Hollywood Gülüşü — Mükemmel Sonuçlar", "✨ Diş İmplantları ile Kalıcı Çözümler", "💎 Zirkonyum Kaplama Uzmanları", "🪥 Diş Beyazlatma Tedavileri", "📞 7/24 Ücretsiz Danışmanlık Hattı"],
    // Services
    sliderCategory: "Diş Tedavileri",
    servicesLabel: "Tedavilerimiz",
    servicesTitle: "Diş Tedavi Hizmetlerimiz",
    servicesDesc: "Kapsamlı diş sağlığı hizmetlerimizle ağız sağlığınızı ve estetik gülüşünüzü güvence altına alın.",
    exploreBtn: "Detaylı İncele →",
    services: [
      { title: "Diş İmplantı", desc: "Eksik dişleriniz için All-on-4 ve All-on-6 sistemleriyle kalıcı çözümler." },
      { title: "Hollywood Gülüşü", desc: "Porselen laminate ve zirkonyum kaplama ile kusursuz diş tasarımı." },
      { title: "Diş Beyazlatma", desc: "Laser beyazlatma ile profesyonel ve hızlı sonuçlar." },
      { title: "Zirkonyum Kaplama", desc: "Estetik ve dayanıklı zirkonyum kaplama ile doğal görünüm." },
      { title: "Kemik Grefti", desc: "Diş implantı için kemik yenileme ve sinus lifting işlemleri." },
      { title: "Diş Plak Tedavisi ve Ortodonti", desc: "Şeffaf plak ve metal tel ile estetik diş hizalama tedavileri." },
    ],
    // Stats
    stats: ["Yıllık Diş Deneyimi", "Başarılı İmplant", "Hollywood Gülüşü", "Hasta Memnuniyeti"],
    // Before After
    beforeAfterBadge: "Gerçek Hasta Sonuçları",
    beforeAfterTitle: "Before & After",
    beforeAfterHighlight: "Dönüşümler",
    beforeAfterDesc: "Haliç Panorama Dental'de tedavi gören gerçek hastalarımızın inanılmaz dönüşümlerini keşfedin. Her görsel, ekibimizin mükemmellik taahhüdünü yansıtmaktadır.",
    trustBar: ["Mutlu Hasta", "Memnuniyet", "Yıl Deneyim", "Ülkeden Hasta"],
    caseLabel: "Vaka",
    ctaBadge: "Hayalinizdeki Gülüş",
    ctaTitle: "Siz de bu dönüşümü yaşayın",
    ctaDesc: "Ücretsiz konsültasyon randevunuzu alın, uzmanlarımız sizin için en uygun tedaviyi belirlesin.",
    ctaBtn: "Ücretsiz Konsültasyon",
    whatsappBtn: "WhatsApp",
    // Doctors
    doctorsLabel: "Uzmanlarımız",
    doctorsTitle: "Diş Hekimlerimizle Tanışın",
    doctorsDesc: "Tercih ettiğiniz doktoru seçin ve birkaç dakika içinde randevu alın.",
    appointmentBtn: "Randevu Al",
    doctors: [
      { specialty: "Estetik Diş Hekimi & İmplantoloji Uzmanı", exp: "12 yıl deneyim" },
      { specialty: "Ortodonti Uzmanı", exp: "8 yıl deneyim" },
      { specialty: "Periodontoloji & Diş Eti Uzmanı", exp: "10 yıl deneyim" },
      { specialty: "Oral & Maksillofasiyal Cerrahi Uzmanı", exp: "9 yıl deneyim" },
      { specialty: "Restoratif Diş Hekimliği Uzmanı", exp: "7 yıl deneyim" },
      { specialty: "Endodonti Uzmanı", exp: "11 yıl deneyim" },
      { specialty: "Protetik Diş Hekimliği Uzmanı", exp: "6 yıl deneyim" },
    ],
    // Why Us
    whyLabel: "Neden Biz?",
    whyTitle: "Neden Haliç Panorama Dental'i Tercih Etmelisiniz?",
    whyDesc: "Diş tedavinizde doğru klinik seçimi hayat değiştiren bir karardır. Haliç Panorama Dental olarak mükemmel diş sağlığı ve estetik için en iyi deneyimi sunuyoruz.",
    reasons: [
      { title: "Uzman Diş Hekimleri", desc: "Alanında uzmanlaşmış, uluslararası sertifikalı diş hekimlerimiz her prosedürde yılların deneyimini sunar." },
      { title: "Son Teknoloji Ekipman", desc: "3D tomografi, dijital gülüş tasarımı ve laser sistemleriyle en hassas tedavileri gerçekleştiriyoruz." },
      { title: "Steril & Güvenli Ortam", desc: "Uluslararası standartlarda sterilizasyon ve hasta güvenliği protokolleriyle en hijyenik ortamı sunuyoruz." },
      { title: "Hızlı & Konforlu Tedavi", desc: "Tek seansta büyük dönüşümler mümkün. Tedavi sürecinizi mümkün olan en konforlu şekilde tamamlıyoruz." },
    ],
    // Packages
    packagesLabel: "VIP HIZMETLER",
    packagesTitle: "Sizin İçin Düşündük",
    packages: [
      { title: "Havaalanı Transferi", desc: "Havaalanından Panorama Dental'e stressiz bir transfer deneyimi yaşayın. Profesyonel şoförlerimiz sizi terminalde karşılayacak." },
      { title: "Otel Konaklama", desc: "İhtiyaçlarınıza uygun çeşitli olanaklar sunan yakındaki birçok otelle ortaklığımız var." },
      { title: "7/24 Ulaşım", desc: "Ulaşım hizmetlerimiz programınıza uyacak şekilde 7/24 hizmetinizdedir ve zamanında varış ve kalkışları garanti eder." },
      { title: "Tercüman Hizmeti", desc: "Türkiye ziyaretiniz sırasında güvenebileceğiniz her dilde uzmanlaşmış tercümanlarımız mevcuttur." },
    ],
    // Departments
    deptLabel: "Bölümlerimiz",
    deptTitle: "Tüm Diş Tedavi Alanlarımız",
    deptDesc: "Panorama Dental, ağız ve diş sağlığının tüm alanlarında uzman kadrosuyla kapsamlı hizmet sunmaktadır.",
    departments: ["Diş İmplantı", "Hollywood Gülüşü", "Zirkonyum Kaplama", "Diş Beyazlatma", "Porselen Laminate", "Diş Teli & Ortodonti", "Kanal Tedavisi", "Diş Eti Tedavisi", "Kemik Grefti", "All-on-4 / All-on-6", "Çocuk Diş Hekimliği", "Ağız & Diş Bakımı"],
    // Contact
    contactLabel: "İletişim",
    contactTitle: "Ücretsiz Danışmanlık",
    contactDesc: "Sorularınızı bize sormaktan çekinmeyin. Hemen formu doldurun, sizi arayalım.",
    phone: "Telefon", email: "E-posta", address: "Adres",
    freeConsultLine: "7/24 Ücretsiz Danışmanlık",
    namePlaceholder: "Adınız Soyadınız",
    emailPlaceholder: "E-posta Adresiniz",
    phonePlaceholder: "Telefon Numaranız",
    messagePlaceholder: "Mesajınız...",
    sendBtn: "Gönder",
    uploadTitle: "Röntgen veya Fotoğraf Yükle",
    uploadDesc: "JPG, PNG, PDF — Birden fazla dosya seçebilirsiniz",
    whatsappText: "Merhaba, ben",
    // Treatment Detail Page
    treatmentAbout: "Tedavi Hakkında",
    treatmentBenefits: "Avantajlar",
    treatmentProcess: "Tedavi Süreci",
    treatmentCtaBadge: "Ücretsiz Değerlendirme",
    treatmentCtaDesc: "Uzman ekibimiz sizi ücretsiz olarak değerlendirsin ve kişisel tedavi planınızı oluştursun.",
    treatmentCtaBtn1: "WhatsApp ile Yaz",
    treatmentCtaBtn2: "Hemen Ara",
    backHome: "Ana Sayfaya Dön",
    notFound: "Tedavi bulunamadı",
    treatments: {
      "dis-implanti": {
        title: "Diş İmplantı", subtitle: "Dental Implant", emoji: "🦷",
        description: "Diş implantları, eksik dişlerin yerine uygulanan, estetik ve fonksiyonel açıdan en gelişmiş tedavi yöntemlerinden biridir. Çene kemiğine yerleştirilen titanyum implantlar sayesinde doğal dişlere en yakın görünüm ve kullanım konforu sağlanır. Eksik dişler yalnızca estetik bir sorun oluşturmaz; aynı zamanda çiğneme fonksiyonunu olumsuz etkiler ve zamanla çene kemiğinde hacim kaybına yol açabilir. İmplant tedavisi, bu sorunları kalıcı olarak ortadan kaldırarak sağlıklı ve dengeli bir ağız yapısının yeniden kazanılmasını sağlar.",
        benefits: ["Doğal görünüm ve his", "20+ yıl dayanıklılık", "Çevre dişlere zarar vermez", "Kemik erimesini önler", "Yeme-içme rahatlığı", "Özgüven artışı"],
        steps: [
          { step: "1", title: "Muayene & Planlama", desc: "3D tomografi ile kapsamlı ağız analizi ve kişiselleştirilmiş tedavi planı." },
          { step: "2", title: "İmplant Yerleştirme", desc: "Lokal anestezi altında titanyum implantın çene kemiğine uygulanması." },
          { step: "3", title: "İyileşme Süreci", desc: "2–4 aylık osseointegrasyon (kemikle kaynaşma) süreci." },
          { step: "4", title: "Üst Yapı & Teslim", desc: "Zirkonyum veya porselen kron takılarak tamamlanan kusursuz gülüş." },
          { step: "5", title: "Tedavi Süreci", desc: "Tedavi süreci, detaylı bir klinik muayene ve kişiye özel planlama ile başlar. İmplantlar lokal anestezi altında konforlu bir şekilde yerleştirilir. İyileşme sürecinin ardından hastaya özel hazırlanan sabit dişler uygulanarak tedavi tamamlanır." },
        ],
      },
      "hollywood-gulusu": {
        title: "Hollywood Gülüşü", subtitle: "Hollywood Smile", emoji: "✨",
        description: "Hollywood Gülüşü, porselen laminate ve zirkonyum kaplamalar kullanılarak dişlerin şeklini, rengini ve konumunu mükemmelleştiren kapsamlı bir estetik diş tedavisidir.",
        benefits: ["Anında dönüşüm", "Doğal porselen görünümü", "Leke tutmaz yapı", "Minimum diş törpüleme", "10–15 yıl ömür", "Özgüven patlaması"],
        steps: [
          { step: "1", title: "Dijital Gülüş Tasarımı", desc: "Bilgisayar ortamında kişiselleştirilmiş gülüş simülasyonu." },
          { step: "2", title: "Mock-Up Uygulama", desc: "Geçici kaplama ile sonucu önce deneyin, onaylayın." },
          { step: "3", title: "Laminatların Yapıştırılması", desc: "0.3–0.5 mm ince porselen laminatlar dişlere yapıştırılır." },
          { step: "4", title: "Son Rötuşlar", desc: "Renk, şekil ve ısırış kontrolü. Hayalinizdeki gülüş teslim edilir." },
        ],
      },
      "dis-beyazlatma": {
        title: "Diş Beyazlatma", subtitle: "Teeth Whitening", emoji: "🪥",
        description: "Profesyonel laser diş beyazlatma ile dişlerinizi 8 tona kadar açın. Klinik ortamında uygulanan güvenli beyazlatma jeli ve LED/laser aktivasyonu ile hızlı ve kalıcı sonuçlar.",
        benefits: ["1 seansta 8 ton açılma", "Diş minesine zarar vermez", "Anında görünür sonuç", "Uzun ömürlü etki", "Ağrısız prosedür", "FDA onaylı ürünler"],
        steps: [
          { step: "1", title: "Diş Yüzeyi Temizliği", desc: "Tartar ve plak temizliği ile beyazlatma öncesi hazırlık." },
          { step: "2", title: "Diş Eti Koruması", desc: "Jel ve ışık bariyeri ile diş etleri korunur." },
          { step: "3", title: "Beyazlatma Jeli & Laser", desc: "Aktif karbojen peroksit jeli uygulanır, laser ile aktive edilir." },
          { step: "4", title: "Koruyucu Flor", desc: "Seans sonunda dişlere güçlendirici flor uygulanır." },
        ],
      },
      "zirkonyum-kaplama": {
        title: "Zirkonyum Kaplama", subtitle: "Zirconia Crown", emoji: "💎",
        description: "Zirkonyum kaplamalar, metal altyapısız tam seramik yapısıyla en doğal görünümü sunan diş kaplamasıdır. Işık geçirgenliği sayesinde doğal dişten ayırt edilemez.",
        benefits: ["Metal içermez", "Işık geçirgen doğal görünüm", "Alerjik reaksiyon riski sıfır", "Yüksek kırılma direnci", "15+ yıl ömür", "Tam renk uyumu"],
        steps: [
          { step: "1", title: "Diş Hazırlığı", desc: "Minimum diş kesimi ile mükemmel altyapı hazırlanır." },
          { step: "2", title: "Ölçü & Tasarım", desc: "Dijital ağız ölçüsü alınır, CAD/CAM sistemiyle tasarlanır." },
          { step: "3", title: "Geçici Kaplama", desc: "Laboratuvar süreci boyunca geçici estetik kaplama takılır." },
          { step: "4", title: "Kalıcı Yapıştırma", desc: "Zirkonyum kronlar hassas adeziv ile kalıcı olarak yapıştırılır." },
        ],
      },
      "kemik-grefti": {
        title: "Kemik Grefti", subtitle: "Bone Graft", emoji: "🦴",
        description: "Kemik grefti, diş kaybına bağlı kemik erimesi olan hastalarda implant uygulaması öncesi kemik hacmini yeniden kazandıran cerrahi bir prosedürdür.",
        benefits: ["İmplant öncesi zemin hazırlar", "Kemik erimesini durdurur", "Yüz konturlarını korur", "Başarı oranı %95+", "Minimal invazif teknikler", "Sinus lifting seçeneği"],
        steps: [
          { step: "1", title: "Kemik Analizi", desc: "3D CBCT tomografi ile kemik yoğunluğu ve hacmi ölçülür." },
          { step: "2", title: "Greft Materyali Seçimi", desc: "Otolog, allograft veya sentetik greft materyali planlanır." },
          { step: "3", title: "Cerrahi Uygulama", desc: "Lokal anestezi altında kemik grefti yerleştirilir." },
          { step: "4", title: "İyileşme & İmplant", desc: "3–6 ay iyileşme sonrası implant uygulamasına geçilir." },
        ],
      },
      "dis-teli-ortodonti": {
        title: "Diş Teli & Ortodonti", subtitle: "Orthodontics", emoji: "😁",
        description: "Modern ortodonti tedavileriyle çarpık, sıkışık veya aralıklı dişlerinizi düzeltin. Şeffaf plaktan metal tele geniş seçenek yelpazesiyle her yaşa uygun çözümler.",
        benefits: ["Şeffaf plak seçeneği", "Görünmez tel teknolojisi", "Her yaşa uygun", "Ağız sağlığını iyileştirir", "Kalıcı sonuçlar", "Dijital simülasyon"],
        steps: [
          { step: "1", title: "Ortodontik Muayene", desc: "Diş modeli, röntgen ve fotoğraf analizi ile kapsamlı değerlendirme." },
          { step: "2", title: "Tedavi Planı", desc: "Kişiselleştirilmiş ortodontik tedavi planı ve süre tahmini." },
          { step: "3", title: "Aparey Uygulaması", desc: "Seçilen sistem (şeffaf plak, metal veya seramik tel) takılır." },
          { step: "4", title: "Retansiyon", desc: "Tedavi sonrası pekiştirici plak ile kalıcı sonuç korunur." },
        ],
      },
    },
  },
  en: {
    nav: ["Home", "About Us", "Services", "Operations", "Contact Us"],
    freeConsult: "Free Consultation",
    heroBadge: "Istanbul, Turkey — Haliç Panorama Dental",
    heroTitle1: "Achieve Your",
    heroTitleHighlight: "Dream Smile",
    heroTitle2: "",
    heroDesc: "Rediscover your confidence with Hollywood smile, dental implants and cosmetic dental treatments. A VIP experience from airport transfer to the clinic.",
    heroCta: "Dental Treatments",
    marquee: ["🦷 Hollywood Smile — Perfect Results", "✨ Permanent Solutions with Dental Implants", "💎 Zirconia Crown Specialists", "🪥 Teeth Whitening Treatments", "📞 24/7 Free Consultation Line"],
    sliderCategory: "Dental Treatments",
    servicesLabel: "Our Treatments",
    servicesTitle: "Dental Treatment Services",
    servicesDesc: "Ensure your oral health and aesthetic smile with our comprehensive dental health services.",
    exploreBtn: "Explore →",
    services: [
      { title: "Dental Implant", desc: "Permanent solutions for missing teeth with All-on-4 and All-on-6 systems." },
      { title: "Hollywood Smile", desc: "Perfect smile design with porcelain laminates and zirconia crowns." },
      { title: "Teeth Whitening", desc: "Professional and fast results with laser whitening." },
      { title: "Zirconia Crown", desc: "Natural appearance with aesthetic and durable zirconia crowns." },
      { title: "Bone Graft", desc: "Bone regeneration and sinus lifting procedures for dental implants." },
      { title: "Braces & Orthodontics", desc: "Aesthetic teeth alignment with clear aligners and metal braces." },
    ],
    stats: ["Years of Experience", "Successful Implants", "Hollywood Smiles", "Patient Satisfaction"],
    beforeAfterBadge: "Real Patient Results",
    beforeAfterTitle: "Before & After",
    beforeAfterHighlight: "Transformations",
    beforeAfterDesc: "Discover the incredible transformations of our real patients treated at Haliç Panorama Dental.",
    trustBar: ["Happy Patients", "Satisfaction", "Years Experience", "Countries"],
    caseLabel: "Case",
    ctaBadge: "Your Dream Smile",
    ctaTitle: "Experience this transformation too",
    ctaDesc: "Book your free consultation, our experts will determine the most suitable treatment for you.",
    ctaBtn: "Free Consultation",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Our Specialists",
    doctorsTitle: "Meet Our Dentists",
    doctorsDesc: "Choose your preferred doctor and get an appointment in minutes.",
    appointmentBtn: "Book Appointment",
    doctors: [
      { specialty: "Aesthetic Dentist & Implantology Specialist", exp: "12 years experience" },
      { specialty: "Orthodontics Specialist", exp: "8 years experience" },
      { specialty: "Periodontology & Gum Specialist", exp: "10 years experience" },
      { specialty: "Oral & Maxillofacial Surgery Specialist", exp: "9 years experience" },
      { specialty: "Restorative Dentistry Specialist", exp: "7 years experience" },
      { specialty: "Endodontics Specialist", exp: "11 years experience" },
      { specialty: "Prosthetic Dentistry Specialist", exp: "6 years experience" },
    ],
    whyLabel: "Why Us?",
    whyTitle: "Why Choose Panorama Dental?",
    whyDesc: "Choosing the right clinic for your dental treatment is a life-changing decision. At Panorama Dental, we offer the best experience for perfect dental health and aesthetics.",
    reasons: [
      { title: "Expert Dentists", desc: "Our internationally certified, specialized dentists bring years of experience to every procedure." },
      { title: "Latest Technology", desc: "We perform the most precise treatments with 3D tomography, digital smile design and laser systems." },
      { title: "Sterile & Safe Environment", desc: "We provide the most hygienic environment with international sterilization and patient safety protocols." },
      { title: "Fast & Comfortable Treatment", desc: "Major transformations possible in a single session. We complete your treatment process as comfortably as possible." },
    ],
    packagesLabel: "VIP SERVICES",
    packagesTitle: "We Thought of You",
    packages: [
      { title: "Airport Transfer", desc: "Enjoy a stress-free transfer from the airport to Panorama Dental. Our professional drivers will meet you at the terminal." },
      { title: "Hotel Accommodation", desc: "We have partnerships with nearby hotels offering a variety of options to suit your needs." },
      { title: "24/7 Transportation", desc: "Our transportation services are available 24/7 to fit your schedule and guarantee timely arrivals and departures." },
      { title: "Interpreter Service", desc: "We have specialized interpreters in every language you can rely on during your visit to Turkey." },
    ],
    deptLabel: "Our Departments",
    deptTitle: "All Dental Treatment Areas",
    deptDesc: "Panorama Dental provides comprehensive services in all areas of oral and dental health with an expert team.",
    departments: ["Dental Implant", "Hollywood Smile", "Zirconia Crown", "Teeth Whitening", "Porcelain Laminate", "Braces & Orthodontics", "Root Canal", "Gum Treatment", "Bone Graft", "All-on-4 / All-on-6", "Pediatric Dentistry", "Oral & Dental Care"],
    contactLabel: "Contact",
    contactTitle: "Free Consultation",
    contactDesc: "Don't hesitate to ask us your questions. Fill in the form now, we'll call you.",
    phone: "Phone", email: "Email", address: "Address",
    freeConsultLine: "24/7 Free Consultation",
    namePlaceholder: "Your Full Name",
    emailPlaceholder: "Your Email Address",
    phonePlaceholder: "Your Phone Number",
    messagePlaceholder: "Your Message...",
    sendBtn: "Send",
    uploadTitle: "Upload X-Ray or Photo",
    uploadDesc: "JPG, PNG, PDF — You can select multiple files",
    whatsappText: "Hello, I am",
    treatmentAbout: "About the Treatment",
    treatmentBenefits: "Benefits",
    treatmentProcess: "Treatment Process",
    treatmentCtaBadge: "Free Evaluation",
    treatmentCtaDesc: "Let our expert team evaluate you for free and create your personal treatment plan.",
    treatmentCtaBtn1: "Write on WhatsApp",
    treatmentCtaBtn2: "Call Now",
    backHome: "Back to Home",
    notFound: "Treatment not found",
    treatments: {
      "dis-implanti": {
        title: "Dental Implant", subtitle: "Dental Implant", emoji: "🦷",
        description: "A dental implant is the most permanent and natural-looking solution for missing teeth. The titanium screw-shaped implant is placed in the jawbone to create a base similar to a natural tooth root.",
        benefits: ["Natural look and feel", "20+ years durability", "No damage to adjacent teeth", "Prevents bone loss", "Comfortable eating and drinking", "Confidence boost"],
        steps: [
          { step: "1", title: "Examination & Planning", desc: "Comprehensive oral analysis with 3D tomography and personalized treatment plan." },
          { step: "2", title: "Implant Placement", desc: "Titanium implant applied to the jawbone under local anesthesia." },
          { step: "3", title: "Healing Process", desc: "2–4 month osseointegration (bone fusion) process." },
          { step: "4", title: "Superstructure & Delivery", desc: "Perfect smile completed with zirconia or porcelain crown." },
        ],
      },
      "hollywood-gulusu": {
        title: "Hollywood Smile", subtitle: "Hollywood Smile", emoji: "✨",
        description: "Hollywood Smile is a comprehensive aesthetic dental treatment that perfects the shape, color and position of teeth using porcelain laminates and zirconia crowns.",
        benefits: ["Instant transformation", "Natural porcelain look", "Stain-resistant", "Minimal tooth filing", "10–15 year lifespan", "Confidence explosion"],
        steps: [
          { step: "1", title: "Digital Smile Design", desc: "Personalized smile simulation on computer." },
          { step: "2", title: "Mock-Up Application", desc: "Try and approve the result with a temporary veneer first." },
          { step: "3", title: "Laminate Bonding", desc: "0.3–0.5 mm thin porcelain laminates are bonded to teeth." },
          { step: "4", title: "Final Touches", desc: "Color, shape and bite check. Your dream smile is delivered." },
        ],
      },
      "dis-beyazlatma": {
        title: "Teeth Whitening", subtitle: "Teeth Whitening", emoji: "🪥",
        description: "Lighten your teeth up to 8 shades with professional laser teeth whitening. Fast and lasting results with safe whitening gel and LED/laser activation applied in a clinical setting.",
        benefits: ["8 shades in 1 session", "No enamel damage", "Instantly visible result", "Long-lasting effect", "Painless procedure", "FDA-approved products"],
        steps: [
          { step: "1", title: "Tooth Surface Cleaning", desc: "Preparation before whitening with tartar and plaque removal." },
          { step: "2", title: "Gum Protection", desc: "Gums are protected with gel and light barrier." },
          { step: "3", title: "Whitening Gel & Laser", desc: "Active carbogen peroxide gel applied and activated with laser." },
          { step: "4", title: "Protective Fluoride", desc: "Strengthening fluoride applied to teeth at end of session." },
        ],
      },
      "zirkonyum-kaplama": {
        title: "Zirconia Crown", subtitle: "Zirconia Crown", emoji: "💎",
        description: "Zirconia crowns are the most natural-looking dental crown with full ceramic structure without metal substructure. Thanks to light transmittance, they are indistinguishable from natural teeth.",
        benefits: ["Metal-free", "Light-transmitting natural look", "Zero allergic reaction risk", "High fracture resistance", "15+ year lifespan", "Perfect color match"],
        steps: [
          { step: "1", title: "Tooth Preparation", desc: "Perfect infrastructure prepared with minimal tooth cutting." },
          { step: "2", title: "Impression & Design", desc: "Digital oral impression taken, designed with CAD/CAM system." },
          { step: "3", title: "Temporary Crown", desc: "Temporary aesthetic crown placed during laboratory process." },
          { step: "4", title: "Permanent Bonding", desc: "Zirconia crowns permanently bonded with precision adhesive." },
        ],
      },
      "kemik-grefti": {
        title: "Bone Graft", subtitle: "Bone Graft", emoji: "🦴",
        description: "Bone graft is a surgical procedure that restores bone volume before implant application in patients with bone loss due to tooth loss.",
        benefits: ["Prepares ground for implant", "Stops bone loss", "Preserves facial contours", "95%+ success rate", "Minimally invasive techniques", "Sinus lifting option"],
        steps: [
          { step: "1", title: "Bone Analysis", desc: "Bone density and volume measured with 3D CBCT tomography." },
          { step: "2", title: "Graft Material Selection", desc: "Autologous, allograft or synthetic graft material planned." },
          { step: "3", title: "Surgical Application", desc: "Bone graft placed under local anesthesia." },
          { step: "4", title: "Healing & Implant", desc: "Implant application after 3–6 months of healing." },
        ],
      },
      "dis-teli-ortodonti": {
        title: "Braces & Orthodontics", subtitle: "Orthodontics", emoji: "😁",
        description: "Correct crooked, crowded or spaced teeth with modern orthodontic treatments. Solutions suitable for all ages with a wide range of options from clear aligners to metal braces.",
        benefits: ["Clear aligner option", "Invisible wire technology", "Suitable for all ages", "Improves oral health", "Permanent results", "Digital simulation"],
        steps: [
          { step: "1", title: "Orthodontic Examination", desc: "Comprehensive evaluation with tooth model, X-ray and photo analysis." },
          { step: "2", title: "Treatment Plan", desc: "Personalized orthodontic treatment plan and duration estimate." },
          { step: "3", title: "Appliance Application", desc: "Selected system (clear aligner, metal or ceramic wire) fitted." },
          { step: "4", title: "Retention", desc: "Permanent result preserved with retainer after treatment." },
        ],
      },
    },
  },
  de: {
    nav: ["Startseite", "Über Uns", "Leistungen", "Operationen", "Kontakt"],
    freeConsult: "Kostenlose Beratung",
    heroBadge: "Istanbul, Türkei — Haliç Panorama Dental",
    heroTitle1: "Ihr Traum-",
    heroTitleHighlight: "Lächeln",
    heroTitle2: "Verwirklichen",
    heroDesc: "Entdecken Sie Ihr Selbstvertrauen mit Hollywood-Lächeln, Zahnimplantaten und kosmetischen Zahnbehandlungen. Ein VIP-Erlebnis vom Flughafentransfer bis zur Klinik.",
    heroCta: "Zahnbehandlungen",
    marquee: ["🦷 Hollywood-Lächeln — Perfekte Ergebnisse", "✨ Dauerhafte Lösungen mit Zahnimplantaten", "💎 Zirkon-Spezialisten", "🪥 Zahnaufhellung", "📞 24/7 Kostenlose Beratung"],
    sliderCategory: "Zahnbehandlungen",
    servicesLabel: "Unsere Behandlungen",
    servicesTitle: "Zahnmedizinische Leistungen",
    servicesDesc: "Sichern Sie Ihre Mundgesundheit und Ihr ästhetisches Lächeln mit unseren umfassenden Dienstleistungen.",
    exploreBtn: "Mehr erfahren →",
    services: [
      { title: "Zahnimplantat", desc: "Dauerhafte Lösungen für fehlende Zähne mit All-on-4 und All-on-6 Systemen." },
      { title: "Hollywood-Lächeln", desc: "Perfektes Lächeln-Design mit Porzellanschalen und Zirkonkronen." },
      { title: "Zahnaufhellung", desc: "Professionelle und schnelle Ergebnisse mit Laser-Bleaching." },
      { title: "Zirkonkrone", desc: "Natürliches Aussehen mit ästhetischen und haltbaren Zirkonkronen." },
      { title: "Knochentransplantat", desc: "Knochenregeneration und Sinuslift für Zahnimplantate." },
      { title: "Zahnspange & Kieferorthopädie", desc: "Ästhetische Zahnkorrektur mit transparenten und Metallspangen." },
    ],
    stats: ["Jahre Erfahrung", "Erfolgreiche Implantate", "Hollywood-Lächeln", "Patientenzufriedenheit"],
    beforeAfterBadge: "Echte Patientenergebnisse",
    beforeAfterTitle: "Vorher & Nachher",
    beforeAfterHighlight: "Transformationen",
    beforeAfterDesc: "Entdecken Sie die unglaublichen Transformationen unserer echten Patienten in Haliç Panorama Dental.",
    trustBar: ["Zufriedene Patienten", "Zufriedenheit", "Jahre Erfahrung", "Länder"],
    caseLabel: "Fall",
    ctaBadge: "Ihr Traumlächeln",
    ctaTitle: "Erleben Sie auch diese Transformation",
    ctaDesc: "Buchen Sie Ihre kostenlose Beratung, unsere Experten bestimmen die geeignetste Behandlung für Sie.",
    ctaBtn: "Kostenlose Beratung",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Unsere Spezialisten",
    doctorsTitle: "Lernen Sie unsere Zahnärzte kennen",
    doctorsDesc: "Wählen Sie Ihren bevorzugten Arzt und vereinbaren Sie in wenigen Minuten einen Termin.",
    appointmentBtn: "Termin buchen",
    doctors: [
      { specialty: "Ästhetische Zahnärztin & Implantologie-Spezialistin", exp: "12 Jahre Erfahrung" },
      { specialty: "Kieferorthopädie-Spezialist", exp: "8 Jahre Erfahrung" },
      { specialty: "Parodontologie & Zahnfleisch-Spezialistin", exp: "10 Jahre Erfahrung" },
      { specialty: "Mund- & Kieferchirurgie-Spezialist", exp: "9 Jahre Erfahrung" },
      { specialty: "Restaurative Zahnheilkunde Spezialist", exp: "7 Jahre Erfahrung" },
      { specialty: "Endodontie-Spezialist", exp: "11 Jahre Erfahrung" },
      { specialty: "Prothetische Zahnheilkunde Spezialist", exp: "6 Jahre Erfahrung" },
    ],
    whyLabel: "Warum wir?",
    whyTitle: "Warum Panorama Dental wählen?",
    whyDesc: "Die Wahl der richtigen Klinik für Ihre Zahnbehandlung ist eine lebensverändernde Entscheidung.",
    reasons: [
      { title: "Experten-Zahnärzte", desc: "Unsere international zertifizierten Zahnärzte bringen jahrelange Erfahrung bei jedem Eingriff mit." },
      { title: "Neueste Technologie", desc: "Wir führen die präzisesten Behandlungen mit 3D-Tomographie und Lasersystemen durch." },
      { title: "Sterile & Sichere Umgebung", desc: "Wir bieten die hygienischste Umgebung mit internationalen Sterilisationsprotokollen." },
      { title: "Schnelle & Komfortable Behandlung", desc: "Große Transformationen in einer einzigen Sitzung möglich." },
    ],
    packagesLabel: "VIP SERVICES",
    packagesTitle: "Wir haben an Sie gedacht",
    packages: [
      { title: "Flughafentransfer", desc: "Genießen Sie einen stressfreien Transfer vom Flughafen zu Panorama Dental." },
      { title: "Hotelunterkunft", desc: "Wir haben Partnerschaften mit nahe gelegenen Hotels, die verschiedene Optionen bieten." },
      { title: "24/7 Transport", desc: "Unsere Transportdienste sind rund um die Uhr verfügbar." },
      { title: "Dolmetscherdienst", desc: "Wir haben spezialisierte Dolmetscher in jeder Sprache für Ihren Türkei-Besuch." },
    ],
    deptLabel: "Unsere Abteilungen",
    deptTitle: "Alle Zahnbehandlungsbereiche",
    deptDesc: "Panorama Dental bietet umfassende Dienstleistungen in allen Bereichen der Mund- und Zahngesundheit.",
    departments: ["Zahnimplantat", "Hollywood-Lächeln", "Zirkonkrone", "Zahnaufhellung", "Porzellanfacette", "Zahnspange & Kieferorthopädie", "Wurzelkanal", "Zahnfleischbehandlung", "Knochentransplantat", "All-on-4 / All-on-6", "Kinderzahnheilkunde", "Mund- & Zahnpflege"],
    contactLabel: "Kontakt",
    contactTitle: "Kostenlose Beratung",
    contactDesc: "Stellen Sie uns Ihre Fragen. Füllen Sie das Formular aus, wir rufen Sie zurück.",
    phone: "Telefon", email: "E-Mail", address: "Adresse",
    freeConsultLine: "24/7 Kostenlose Beratung",
    namePlaceholder: "Ihr vollständiger Name",
    emailPlaceholder: "Ihre E-Mail-Adresse",
    phonePlaceholder: "Ihre Telefonnummer",
    messagePlaceholder: "Ihre Nachricht...",
    sendBtn: "Senden",
    uploadTitle: "Röntgenbild oder Foto hochladen",
    uploadDesc: "JPG, PNG, PDF — Sie können mehrere Dateien auswählen",
    whatsappText: "Hallo, ich bin",
    treatmentAbout: "Über die Behandlung",
    treatmentBenefits: "Vorteile",
    treatmentProcess: "Behandlungsprozess",
    treatmentCtaBadge: "Kostenlose Bewertung",
    treatmentCtaDesc: "Lassen Sie sich von unserem Expertenteam kostenlos bewerten und Ihren persönlichen Behandlungsplan erstellen.",
    treatmentCtaBtn1: "Per WhatsApp schreiben",
    treatmentCtaBtn2: "Jetzt anrufen",
    backHome: "Zurück zur Startseite",
    notFound: "Behandlung nicht gefunden",
    treatments: {
      "dis-implanti": {
        title: "Zahnimplantat", subtitle: "Dental Implant", emoji: "🦷",
        description: "Ein Zahnimplantat ist die dauerhafteste und natürlichste Lösung für fehlende Zähne. Das schraubenförmige Titaniumimplantat wird in den Kieferknochen eingesetzt und bildet eine Basis ähnlich einer natürlichen Zahnwurzel.",
        benefits: ["Natürliches Aussehen und Gefühl", "20+ Jahre Haltbarkeit", "Keine Schäden an benachbarten Zähnen", "Verhindert Knochenschwund", "Komfortables Essen und Trinken", "Selbstvertrauen stärken"],
        steps: [
          { step: "1", title: "Untersuchung & Planung", desc: "Umfassende Mundanalyse mit 3D-Tomographie und personalisiertem Behandlungsplan." },
          { step: "2", title: "Implantateinsetzen", desc: "Titaniumimplantat unter Lokalanästhesie in den Kieferknochen eingesetzt." },
          { step: "3", title: "Heilungsprozess", desc: "2–4 Monate Osseointegration (Knochenfusion)." },
          { step: "4", title: "Aufbau & Lieferung", desc: "Perfektes Lächeln mit Zirkon- oder Porzellankrone vollendet." },
        ],
      },
      "hollywood-gulusu": {
        title: "Hollywood-Lächeln", subtitle: "Hollywood Smile", emoji: "✨",
        description: "Das Hollywood-Lächeln ist eine umfassende ästhetische Zahnbehandlung, die Form, Farbe und Position der Zähne mit Porzellanschalen und Zirkonkronen perfektioniert.",
        benefits: ["Sofortige Transformation", "Natürliches Porzellanlook", "Fleckenresistent", "Minimales Abschleifen", "10–15 Jahre Lebensdauer", "Selbstvertrauensschub"],
        steps: [
          { step: "1", title: "Digitales Lächeln-Design", desc: "Personalisierte Lächelnsimulation am Computer." },
          { step: "2", title: "Mock-Up-Anwendung", desc: "Ergebnis zuerst mit temporärem Veneer ausprobieren und genehmigen." },
          { step: "3", title: "Laminatbondierung", desc: "0,3–0,5 mm dünne Porzellanlaminate werden an Zähnen befestigt." },
          { step: "4", title: "Letzte Korrekturen", desc: "Farbe, Form und Bissprüfung. Ihr Traumlächeln wird geliefert." },
        ],
      },
      "dis-beyazlatma": {
        title: "Zahnaufhellung", subtitle: "Teeth Whitening", emoji: "🪥",
        description: "Hellen Sie Ihre Zähne mit professioneller Laserzahnaufhellung um bis zu 8 Töne auf. Schnelle und dauerhafte Ergebnisse mit sicherem Aufhellungsgel und LED/Laser-Aktivierung.",
        benefits: ["8 Töne in 1 Sitzung", "Keine Emailschäden", "Sofort sichtbares Ergebnis", "Langanhaltende Wirkung", "Schmerzloser Eingriff", "FDA-zugelassene Produkte"],
        steps: [
          { step: "1", title: "Zahnreinigung", desc: "Vorbereitung mit Zahnstein- und Plaqueentfernung." },
          { step: "2", title: "Zahnfleischschutz", desc: "Zahnfleisch wird mit Gel und Lichtbarriere geschützt." },
          { step: "3", title: "Aufhellungsgel & Laser", desc: "Aktives Gel aufgetragen und mit Laser aktiviert." },
          { step: "4", title: "Schutzfluorid", desc: "Stärkendes Fluorid am Ende der Sitzung aufgetragen." },
        ],
      },
      "zirkonyum-kaplama": {
        title: "Zirkonkrone", subtitle: "Zirconia Crown", emoji: "💎",
        description: "Zirkonkronen sind die natürlichste Zahnkrone mit Vollkeramikstruktur ohne Metallunterbau. Dank Lichtdurchlässigkeit sind sie von natürlichen Zähnen nicht zu unterscheiden.",
        benefits: ["Metallfrei", "Lichtdurchlässiges natürliches Aussehen", "Kein Allergierisiko", "Hohe Bruchfestigkeit", "15+ Jahre Lebensdauer", "Perfekte Farbabstimmung"],
        steps: [
          { step: "1", title: "Zahnvorbereitung", desc: "Perfekte Infrastruktur mit minimalem Zahnschnitt." },
          { step: "2", title: "Abformung & Design", desc: "Digitaler Mundabdruck, Design mit CAD/CAM-System." },
          { step: "3", title: "Temporäre Krone", desc: "Temporäre ästhetische Krone während des Laborprozesses." },
          { step: "4", title: "Permanente Befestigung", desc: "Zirkonkronen mit Präzisionskleber permanent befestigt." },
        ],
      },
      "kemik-grefti": {
        title: "Knochentransplantat", subtitle: "Bone Graft", emoji: "🦴",
        description: "Ein Knochentransplantat ist ein chirurgisches Verfahren, das das Knochenvolumen vor der Implantatanwendung bei Patienten mit Knochenschwund wiederherstellt.",
        benefits: ["Bereitet Boden für Implantat", "Stoppt Knochenschwund", "Erhält Gesichtskonturen", "95%+ Erfolgsrate", "Minimalinvasive Techniken", "Sinuslift-Option"],
        steps: [
          { step: "1", title: "Knochenanalyse", desc: "Knochendichte und -volumen mit 3D-CBCT-Tomographie gemessen." },
          { step: "2", title: "Transplantmaterialauswahl", desc: "Autologes, Allograft oder synthetisches Material geplant." },
          { step: "3", title: "Chirurgische Anwendung", desc: "Knochentransplantat unter Lokalanästhesie platziert." },
          { step: "4", title: "Heilung & Implantat", desc: "Implantatanwendung nach 3–6 Monaten Heilung." },
        ],
      },
      "dis-teli-ortodonti": {
        title: "Zahnspange & Kieferorthopädie", subtitle: "Orthodontics", emoji: "😁",
        description: "Korrigieren Sie schiefe, gedrängte oder lückenhafte Zähne mit modernen kieferorthopädischen Behandlungen. Lösungen für alle Altersgruppen.",
        benefits: ["Transparente Schiene", "Unsichtbare Technik", "Für alle Altersgruppen", "Verbessert Mundgesundheit", "Dauerhafte Ergebnisse", "Digitale Simulation"],
        steps: [
          { step: "1", title: "Kieferorthopädische Untersuchung", desc: "Umfassende Bewertung mit Zahnmodell, Röntgen und Fotoanalyse." },
          { step: "2", title: "Behandlungsplan", desc: "Personalisierter kieferorthopädischer Behandlungsplan." },
          { step: "3", title: "Apparaturanwendung", desc: "Ausgewähltes System (transparente Schiene, Metall oder Keramik) eingesetzt." },
          { step: "4", title: "Retention", desc: "Dauerhaftes Ergebnis mit Retainer nach Behandlung gesichert." },
        ],
      },
    },
  },
  ar: {
    nav: ["الرئيسية", "من نحن", "خدماتنا", "العمليات", "اتصل بنا"],
    freeConsult: "استشارة مجانية",
    heroBadge: "إسطنبول، تركيا — Haliç Panorama Dental",
    heroTitle1: "احصل على",
    heroTitleHighlight: "ابتسامة أحلامك",
    heroTitle2: "",
    heroDesc: "أعد اكتشاف ثقتك بنفسك مع ابتسامة هوليوود وزراعة الأسنان وعلاجات الأسنان التجميلية. تجربة VIP من المطار إلى العيادة.",
    heroCta: "علاجات الأسنان",
    marquee: ["🦷 ابتسامة هوليوود — نتائج مثالية", "✨ حلول دائمة بزراعة الأسنان", "💎 متخصصون في تيجان الزركونيا", "🪥 علاجات تبييض الأسنان", "📞 خط استشارة مجاني 24/7"],
    sliderCategory: "علاجات الأسنان",
    servicesLabel: "علاجاتنا",
    servicesTitle: "خدمات علاج الأسنان",
    servicesDesc: "حافظ على صحة فمك وابتسامتك الجمالية من خلال خدماتنا الشاملة لصحة الأسنان.",
    exploreBtn: "استكشف →",
    services: [
      { title: "زراعة الأسنان", desc: "حلول دائمة للأسنان المفقودة بأنظمة All-on-4 وAll-on-6." },
      { title: "ابتسامة هوليوود", desc: "تصميم ابتسامة مثالية بالقشور الخزفية وتيجان الزركونيا." },
      { title: "تبييض الأسنان", desc: "نتائج احترافية وسريعة بتبييض الليزر." },
      { title: "تاج الزركونيا", desc: "مظهر طبيعي بتيجان الزركونيا الجمالية والمتينة." },
      { title: "زراعة العظام", desc: "تجديد العظام ورفع الجيب الأنفي لزراعة الأسنان." },
      { title: "تقويم الأسنان", desc: "محاذاة الأسنان الجمالية بمحاذيات شفافة وتقويم معدني." },
    ],
    stats: ["سنوات خبرة", "زرعة ناجحة", "ابتسامة هوليوود", "رضا المرضى"],
    beforeAfterBadge: "نتائج مرضى حقيقيين",
    beforeAfterTitle: "قبل وبعد",
    beforeAfterHighlight: "التحولات",
    beforeAfterDesc: "اكتشف التحولات المذهلة لمرضانا الحقيقيين الذين عولجوا في Haliç Panorama Dental.",
    trustBar: ["مريض سعيد", "رضا", "سنوات خبرة", "دولة"],
    caseLabel: "حالة",
    ctaBadge: "ابتسامة أحلامك",
    ctaTitle: "عش هذا التحول أنت أيضاً",
    ctaDesc: "احجز استشارتك المجانية، سيحدد خبراؤنا العلاج الأنسب لك.",
    ctaBtn: "استشارة مجانية",
    whatsappBtn: "واتساب",
    doctorsLabel: "متخصصونا",
    doctorsTitle: "تعرف على أطبائنا",
    doctorsDesc: "اختر طبيبك المفضل واحصل على موعد في دقائق.",
    appointmentBtn: "احجز موعداً",
    doctors: [
      { specialty: "طبيبة أسنان تجميلية ومتخصصة في زراعة الأسنان", exp: "12 سنة خبرة" },
      { specialty: "متخصص في تقويم الأسنان", exp: "8 سنوات خبرة" },
      { specialty: "متخصصة في أمراض اللثة", exp: "10 سنوات خبرة" },
      { specialty: "متخصص في جراحة الفم والوجه والفكين", exp: "9 سنوات خبرة" },
      { specialty: "متخصص في طب الأسنان التجديدي", exp: "7 سنوات خبرة" },
      { specialty: "متخصص في علاج جذور الأسنان", exp: "11 سنة خبرة" },
      { specialty: "متخصص في طب الأسنان التعويضي", exp: "6 سنوات خبرة" },
    ],
    whyLabel: "لماذا نحن؟",
    whyTitle: "لماذا تختار باناروما دنتال؟",
    whyDesc: "اختيار العيادة الصحيحة لعلاج أسنانك قرار يغير الحياة.",
    reasons: [
      { title: "أطباء متخصصون", desc: "أطباؤنا المعتمدون دولياً يجلبون سنوات من الخبرة لكل إجراء." },
      { title: "أحدث التقنيات", desc: "نجري أدق العلاجات بالتصوير المقطعي ثلاثي الأبعاد وأنظمة الليزر." },
      { title: "بيئة معقمة وآمنة", desc: "نوفر أكثر البيئات نظافة وفق بروتوكولات التعقيم الدولية." },
      { title: "علاج سريع ومريح", desc: "تحولات كبيرة ممكنة في جلسة واحدة." },
    ],
    packagesLabel: "خدمات VIP",
    packagesTitle: "فكرنا فيك",
    packages: [
      { title: "نقل المطار", desc: "استمتع بنقل خالٍ من التوتر من المطار إلى باناروما دنتال." },
      { title: "إقامة فندقية", desc: "لدينا شراكات مع فنادق قريبة تقدم خيارات متنوعة." },
      { title: "نقل 24/7", desc: "خدمات النقل لدينا متاحة على مدار الساعة." },
      { title: "خدمة الترجمة", desc: "لدينا مترجمون متخصصون بكل اللغات لزيارتك لتركيا." },
    ],
    deptLabel: "أقسامنا",
    deptTitle: "جميع مجالات علاج الأسنان",
    deptDesc: "تقدم باناروما دنتال خدمات شاملة في جميع مجالات صحة الفم والأسنان.",
    departments: ["زراعة الأسنان", "ابتسامة هوليوود", "تاج الزركونيا", "تبييض الأسنان", "قشور البورسلين", "تقويم الأسنان", "علاج الجذور", "علاج اللثة", "زراعة العظام", "All-on-4 / All-on-6", "طب أسنان الأطفال", "العناية بالفم والأسنان"],
    contactLabel: "التواصل",
    contactTitle: "استشارة مجانية",
    contactDesc: "لا تتردد في طرح أسئلتك. املأ النموذج الآن وسنتصل بك.",
    phone: "الهاتف", email: "البريد الإلكتروني", address: "العنوان",
    freeConsultLine: "استشارة مجانية 24/7",
    namePlaceholder: "اسمك الكامل",
    emailPlaceholder: "بريدك الإلكتروني",
    phonePlaceholder: "رقم هاتفك",
    messagePlaceholder: "رسالتك...",
    sendBtn: "إرسال",
    uploadTitle: "تحميل صورة أشعة أو صورة",
    uploadDesc: "JPG، PNG، PDF — يمكنك اختيار ملفات متعددة",
    whatsappText: "مرحباً، أنا",
    treatmentAbout: "عن العلاج",
    treatmentBenefits: "المزايا",
    treatmentProcess: "مسار العلاج",
    treatmentCtaBadge: "تقييم مجاني",
    treatmentCtaDesc: "دع فريقنا المتخصص يقيّمك مجاناً ويضع خطة علاجك الشخصية.",
    treatmentCtaBtn1: "راسلنا على واتساب",
    treatmentCtaBtn2: "اتصل الآن",
    backHome: "العودة إلى الرئيسية",
    notFound: "العلاج غير موجود",
    treatments: {
      "dis-implanti": {
        title: "زراعة الأسنان", subtitle: "Dental Implant", emoji: "🦷",
        description: "زراعة الأسنان هي الحل الأكثر ديمومة وطبيعية للأسنان المفقودة. يُزرع الغرسة التيتانيومية في عظم الفك لتشكّل قاعدة تشبه جذر السن الطبيعي.",
        benefits: ["مظهر وإحساس طبيعي", "متانة أكثر من 20 عاماً", "لا يضر الأسنان المجاورة", "يمنع فقدان العظام", "راحة في الأكل والشرب", "تعزيز الثقة بالنفس"],
        steps: [
          { step: "1", title: "الفحص والتخطيط", desc: "تحليل شامل للفم بالتصوير ثلاثي الأبعاد وخطة علاج مخصصة." },
          { step: "2", title: "زراعة الغرسة", desc: "تثبيت الغرسة التيتانيومية في الفك تحت تخدير موضعي." },
          { step: "3", title: "فترة الشفاء", desc: "عملية التحام العظم (2-4 أشهر)." },
          { step: "4", title: "التركيب والتسليم", desc: "ابتسامة مثالية بتاج الزركون أو البورسلين." },
        ],
      },
      "hollywood-gulusu": {
        title: "ابتسامة هوليوود", subtitle: "Hollywood Smile", emoji: "✨",
        description: "ابتسامة هوليوود علاج تجميلي شامل يُحسّن شكل ولون وموضع الأسنان باستخدام القشور الخزفية وتيجان الزركونيا.",
        benefits: ["تحول فوري", "مظهر خزفي طبيعي", "مقاوم للبقع", "حد أدنى من البرد", "عمر 10-15 سنة", "انفجار الثقة بالنفس"],
        steps: [
          { step: "1", title: "تصميم الابتسامة الرقمي", desc: "محاكاة مخصصة للابتسامة بالحاسوب." },
          { step: "2", title: "تطبيق Mock-Up", desc: "جرّب النتيجة أولاً بقشرة مؤقتة ووافق عليها." },
          { step: "3", title: "تثبيت القشور", desc: "قشور خزفية بسمك 0.3-0.5 مم تُلصق على الأسنان." },
          { step: "4", title: "اللمسات الأخيرة", desc: "فحص اللون والشكل والعضة. تسليم ابتسامة أحلامك." },
        ],
      },
      "dis-beyazlatma": {
        title: "تبييض الأسنان", subtitle: "Teeth Whitening", emoji: "🪥",
        description: "افتح أسنانك حتى 8 درجات بتبييض الليزر الاحترافي. نتائج سريعة ودائمة بجل التبييض الآمن وتفعيل LED/الليزر في بيئة سريرية.",
        benefits: ["8 درجات في جلسة واحدة", "لا يتلف المينا", "نتيجة فورية مرئية", "تأثير طويل الأمد", "إجراء غير مؤلم", "منتجات معتمدة من FDA"],
        steps: [
          { step: "1", title: "تنظيف سطح الأسنان", desc: "إزالة الجير واللويحات كتحضير للتبييض." },
          { step: "2", title: "حماية اللثة", desc: "حماية اللثة بالجل وحاجز الضوء." },
          { step: "3", title: "جل التبييض والليزر", desc: "تطبيق جل بيروكسيد الكربوجين وتفعيله بالليزر." },
          { step: "4", title: "فلوريد وقائي", desc: "تطبيق فلوريد مقوي على الأسنان في نهاية الجلسة." },
        ],
      },
      "zirkonyum-kaplama": {
        title: "تاج الزركونيا", subtitle: "Zirconia Crown", emoji: "💎",
        description: "تيجان الزركونيا هي أكثر تيجان الأسنان طبيعية بهيكل خزفي كامل بدون قاعدة معدنية. بفضل شفافية الضوء لا يمكن تمييزها عن الأسنان الطبيعية.",
        benefits: ["خالية من المعدن", "مظهر طبيعي شفاف", "لا خطر الحساسية", "مقاومة عالية للكسر", "عمر 15+ سنة", "تطابق لوني مثالي"],
        steps: [
          { step: "1", title: "تحضير السن", desc: "بنية تحتية مثالية بأدنى قطع للسن." },
          { step: "2", title: "البصمة والتصميم", desc: "بصمة رقمية للفم وتصميم بنظام CAD/CAM." },
          { step: "3", title: "التاج المؤقت", desc: "تاج جمالي مؤقت خلال عملية المختبر." },
          { step: "4", title: "التثبيت الدائم", desc: "تيجان الزركونيا مثبتة بشكل دائم بلاصق دقيق." },
        ],
      },
      "kemik-grefti": {
        title: "زراعة العظام", subtitle: "Bone Graft", emoji: "🦴",
        description: "زراعة العظام إجراء جراحي يستعيد حجم العظم قبل تطبيق الغرسة لدى المرضى الذين يعانون من فقدان العظام بسبب فقدان الأسنان.",
        benefits: ["تحضير الأرض للغرسة", "إيقاف فقدان العظام", "الحفاظ على ملامح الوجه", "معدل نجاح 95%+", "تقنيات طفيفة التوغل", "خيار رفع الجيب الأنفي"],
        steps: [
          { step: "1", title: "تحليل العظام", desc: "قياس كثافة وحجم العظام بتصوير CBCT ثلاثي الأبعاد." },
          { step: "2", title: "اختيار المادة", desc: "تخطيط مادة طعم ذاتي أو خيفي أو اصطناعي." },
          { step: "3", title: "التطبيق الجراحي", desc: "زراعة العظام تحت تخدير موضعي." },
          { step: "4", title: "الشفاء والغرسة", desc: "تطبيق الغرسة بعد 3-6 أشهر من الشفاء." },
        ],
      },
      "dis-teli-ortodonti": {
        title: "تقويم الأسنان", subtitle: "Orthodontics", emoji: "😁",
        description: "صحح أسنانك المعوجة أو المتراكبة أو المتباعدة بعلاجات تقويمية حديثة. حلول مناسبة لجميع الأعمار.",
        benefits: ["خيار المحاذي الشفاف", "تقنية سلك غير مرئي", "مناسب لجميع الأعمار", "يحسن صحة الفم", "نتائج دائمة", "محاكاة رقمية"],
        steps: [
          { step: "1", title: "الفحص التقويمي", desc: "تقييم شامل بنموذج الأسنان والأشعة وتحليل الصور." },
          { step: "2", title: "خطة العلاج", desc: "خطة علاج تقويمي مخصصة وتقدير المدة." },
          { step: "3", title: "تركيب الجهاز", desc: "تركيب النظام المختار (محاذي شفاف أو سلك معدني أو خزفي)." },
          { step: "4", title: "التثبيت", desc: "الحفاظ على النتيجة الدائمة بجهاز تثبيت بعد العلاج." },
        ],
      },
    },
  },
  es: {
    nav: ["Inicio", "Sobre Nosotros", "Servicios", "Operaciones", "Contáctenos"],
    freeConsult: "Consulta Gratuita",
    heroBadge: "Estambul, Turquía — Haliç Panorama Dental",
    heroTitle1: "Consiga su",
    heroTitleHighlight: "Sonrisa Soñada",
    heroTitle2: "",
    heroDesc: "Redescubra su confianza con sonrisa Hollywood, implantes dentales y tratamientos cosméticos. Una experiencia VIP desde el aeropuerto hasta la clínica.",
    heroCta: "Tratamientos Dentales",
    marquee: ["🦷 Sonrisa Hollywood — Resultados Perfectos", "✨ Soluciones Permanentes con Implantes Dentales", "💎 Especialistas en Coronas de Zirconio", "🪥 Tratamientos de Blanqueamiento", "📞 Línea de Consulta Gratuita 24/7"],
    sliderCategory: "Tratamientos Dentales",
    servicesLabel: "Nuestros Tratamientos",
    servicesTitle: "Servicios de Tratamiento Dental",
    servicesDesc: "Asegure su salud bucal y sonrisa estética con nuestros servicios integrales de salud dental.",
    exploreBtn: "Explorar →",
    services: [
      { title: "Implante Dental", desc: "Soluciones permanentes para dientes perdidos con sistemas All-on-4 y All-on-6." },
      { title: "Sonrisa Hollywood", desc: "Diseño de sonrisa perfecto con carillas de porcelana y coronas de zirconio." },
      { title: "Blanqueamiento Dental", desc: "Resultados profesionales y rápidos con blanqueamiento láser." },
      { title: "Corona de Zirconio", desc: "Apariencia natural con coronas de zirconio estéticas y duraderas." },
      { title: "Injerto Óseo", desc: "Regeneración ósea y elevación de seno para implantes dentales." },
      { title: "Ortodoncia", desc: "Alineación dental estética con alineadores transparentes y brackets metálicos." },
    ],
    stats: ["Años de Experiencia", "Implantes Exitosos", "Sonrisas Hollywood", "Satisfacción del Paciente"],
    beforeAfterBadge: "Resultados de Pacientes Reales",
    beforeAfterTitle: "Antes & Después",
    beforeAfterHighlight: "Transformaciones",
    beforeAfterDesc: "Descubra las increíbles transformaciones de nuestros pacientes reales tratados en Haliç Panorama Dental.",
    trustBar: ["Pacientes Felices", "Satisfacción", "Años Experiencia", "Países"],
    caseLabel: "Caso",
    ctaBadge: "Tu Sonrisa Soñada",
    ctaTitle: "Vive también esta transformación",
    ctaDesc: "Reserve su consulta gratuita, nuestros expertos determinarán el tratamiento más adecuado para usted.",
    ctaBtn: "Consulta Gratuita",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Nuestros Especialistas",
    doctorsTitle: "Conozca a Nuestros Dentistas",
    doctorsDesc: "Elija su médico preferido y obtenga una cita en minutos.",
    appointmentBtn: "Reservar Cita",
    doctors: [
      { specialty: "Dentista Estética & Especialista en Implantología", exp: "12 años de experiencia" },
      { specialty: "Especialista en Ortodoncia", exp: "8 años de experiencia" },
      { specialty: "Especialista en Periodoncia & Encías", exp: "10 años de experiencia" },
      { specialty: "Especialista en Cirugía Oral & Maxilofacial", exp: "9 años de experiencia" },
      { specialty: "Especialista en Odontología Restauradora", exp: "7 años de experiencia" },
      { specialty: "Especialista en Endodoncia", exp: "11 años de experiencia" },
      { specialty: "Especialista en Odontología Protésica", exp: "6 años de experiencia" },
    ],
    whyLabel: "¿Por Qué Nosotros?",
    whyTitle: "¿Por Qué Elegir Panorama Dental?",
    whyDesc: "Elegir la clínica correcta para su tratamiento dental es una decisión que cambia la vida.",
    reasons: [
      { title: "Dentistas Expertos", desc: "Nuestros dentistas certificados internacionalmente aportan años de experiencia a cada procedimiento." },
      { title: "Última Tecnología", desc: "Realizamos los tratamientos más precisos con tomografía 3D y sistemas láser." },
      { title: "Entorno Estéril y Seguro", desc: "Ofrecemos el entorno más higiénico con protocolos de esterilización internacionales." },
      { title: "Tratamiento Rápido y Cómodo", desc: "Grandes transformaciones posibles en una sola sesión." },
    ],
    packagesLabel: "SERVICIOS VIP",
    packagesTitle: "Pensamos en Usted",
    packages: [
      { title: "Traslado al Aeropuerto", desc: "Disfrute de un traslado sin estrés desde el aeropuerto a Panorama Dental." },
      { title: "Alojamiento en Hotel", desc: "Tenemos asociaciones con hoteles cercanos que ofrecen diversas opciones." },
      { title: "Transporte 24/7", desc: "Nuestros servicios de transporte están disponibles las 24 horas." },
      { title: "Servicio de Intérprete", desc: "Tenemos intérpretes especializados en todos los idiomas para su visita a Turquía." },
    ],
    deptLabel: "Nuestros Departamentos",
    deptTitle: "Todas las Áreas de Tratamiento Dental",
    deptDesc: "Panorama Dental ofrece servicios integrales en todas las áreas de la salud bucal y dental.",
    departments: ["Implante Dental", "Sonrisa Hollywood", "Corona de Zirconio", "Blanqueamiento Dental", "Carilla de Porcelana", "Ortodoncia", "Endodoncia", "Tratamiento de Encías", "Injerto Óseo", "All-on-4 / All-on-6", "Odontopediatría", "Cuidado Oral"],
    contactLabel: "Contacto",
    contactTitle: "Consulta Gratuita",
    contactDesc: "No dude en hacernos sus preguntas. Rellene el formulario, le llamaremos.",
    phone: "Teléfono", email: "Correo Electrónico", address: "Dirección",
    freeConsultLine: "Consulta Gratuita 24/7",
    namePlaceholder: "Su Nombre Completo",
    emailPlaceholder: "Su Correo Electrónico",
    phonePlaceholder: "Su Número de Teléfono",
    messagePlaceholder: "Su Mensaje...",
    sendBtn: "Enviar",
    uploadTitle: "Subir Radiografía o Foto",
    uploadDesc: "JPG, PNG, PDF — Puede seleccionar varios archivos",
    whatsappText: "Hola, soy",
    treatmentAbout: "Sobre el Tratamiento",
    treatmentBenefits: "Beneficios",
    treatmentProcess: "Proceso de Tratamiento",
    treatmentCtaBadge: "Evaluación Gratuita",
    treatmentCtaDesc: "Deje que nuestro equipo experto le evalúe gratuitamente y cree su plan de tratamiento personal.",
    treatmentCtaBtn1: "Escribir por WhatsApp",
    treatmentCtaBtn2: "Llamar Ahora",
    backHome: "Volver al Inicio",
    notFound: "Tratamiento no encontrado",
    treatments: {
      "dis-implanti": {
        title: "Implante Dental", subtitle: "Dental Implant", emoji: "🦷",
        description: "Un implante dental es la solución más permanente y de aspecto natural para los dientes perdidos. El implante de titanio se coloca en el hueso mandibular para crear una base similar a la raíz dental natural.",
        benefits: ["Apariencia y sensación natural", "Durabilidad de 20+ años", "Sin daño a dientes adyacentes", "Previene pérdida ósea", "Comodidad al comer y beber", "Aumento de confianza"],
        steps: [
          { step: "1", title: "Examen y Planificación", desc: "Análisis oral completo con tomografía 3D y plan de tratamiento personalizado." },
          { step: "2", title: "Colocación del Implante", desc: "Implante de titanio colocado en el maxilar bajo anestesia local." },
          { step: "3", title: "Proceso de Curación", desc: "Proceso de oseointegración (fusión ósea) de 2-4 meses." },
          { step: "4", title: "Superestructura y Entrega", desc: "Sonrisa perfecta completada con corona de zirconio o porcelana." },
        ],
      },
      "hollywood-gulusu": {
        title: "Sonrisa Hollywood", subtitle: "Hollywood Smile", emoji: "✨",
        description: "La Sonrisa Hollywood es un tratamiento dental estético integral que perfecciona la forma, el color y la posición de los dientes usando carillas de porcelana y coronas de zirconio.",
        benefits: ["Transformación instantánea", "Aspecto natural de porcelana", "Resistente a manchas", "Mínimo limado", "Vida útil 10-15 años", "Explosión de confianza"],
        steps: [
          { step: "1", title: "Diseño Digital de Sonrisa", desc: "Simulación personalizada de sonrisa en computadora." },
          { step: "2", title: "Aplicación Mock-Up", desc: "Pruebe y apruebe el resultado con una carilla temporal." },
          { step: "3", title: "Adhesión de Laminados", desc: "Laminados de porcelana de 0.3-0.5 mm adheridos a los dientes." },
          { step: "4", title: "Toques Finales", desc: "Control de color, forma y mordida. Su sonrisa soñada es entregada." },
        ],
      },
      "dis-beyazlatma": {
        title: "Blanqueamiento Dental", subtitle: "Teeth Whitening", emoji: "🪥",
        description: "Aclare sus dientes hasta 8 tonos con blanqueamiento dental profesional láser. Resultados rápidos y duraderos con gel blanqueador seguro y activación LED/láser en entorno clínico.",
        benefits: ["8 tonos en 1 sesión", "Sin daño al esmalte", "Resultado visible al instante", "Efecto duradero", "Procedimiento indoloro", "Productos aprobados FDA"],
        steps: [
          { step: "1", title: "Limpieza de Superficie", desc: "Preparación con eliminación de sarro y placa." },
          { step: "2", title: "Protección de Encías", desc: "Encías protegidas con gel y barrera de luz." },
          { step: "3", title: "Gel Blanqueador y Láser", desc: "Gel de peróxido aplicado y activado con láser." },
          { step: "4", title: "Flúor Protector", desc: "Flúor fortalecedor aplicado al final de la sesión." },
        ],
      },
      "zirkonyum-kaplama": {
        title: "Corona de Zirconio", subtitle: "Zirconia Crown", emoji: "💎",
        description: "Las coronas de zirconio son la corona dental más natural con estructura totalmente cerámica sin subestructura metálica. Gracias a la transmisión de luz son indistinguibles de los dientes naturales.",
        benefits: ["Sin metal", "Aspecto natural translúcido", "Cero riesgo alérgico", "Alta resistencia a la fractura", "Vida útil 15+ años", "Coincidencia de color perfecta"],
        steps: [
          { step: "1", title: "Preparación Dental", desc: "Infraestructura perfecta con mínimo corte dental." },
          { step: "2", title: "Impresión y Diseño", desc: "Impresión oral digital, diseño con sistema CAD/CAM." },
          { step: "3", title: "Corona Temporal", desc: "Corona estética temporal durante el proceso de laboratorio." },
          { step: "4", title: "Adhesión Permanente", desc: "Coronas de zirconio adheridas permanentemente con adhesivo de precisión." },
        ],
      },
      "kemik-grefti": {
        title: "Injerto Óseo", subtitle: "Bone Graft", emoji: "🦴",
        description: "El injerto óseo es un procedimiento quirúrgico que restaura el volumen óseo antes de la aplicación de implantes en pacientes con pérdida ósea.",
        benefits: ["Prepara terreno para implante", "Detiene pérdida ósea", "Preserva contornos faciales", "Tasa de éxito 95%+", "Técnicas mínimamente invasivas", "Opción de elevación de seno"],
        steps: [
          { step: "1", title: "Análisis Óseo", desc: "Densidad y volumen óseo medidos con tomografía 3D CBCT." },
          { step: "2", title: "Selección de Material", desc: "Material de injerto autólogo, aloinjerto o sintético planificado." },
          { step: "3", title: "Aplicación Quirúrgica", desc: "Injerto óseo colocado bajo anestesia local." },
          { step: "4", title: "Curación e Implante", desc: "Aplicación de implante tras 3-6 meses de curación." },
        ],
      },
      "dis-teli-ortodonti": {
        title: "Ortodoncia", subtitle: "Orthodontics", emoji: "😁",
        description: "Corrija dientes torcidos, apiñados o espaciados con tratamientos ortodóncicos modernos. Soluciones para todas las edades.",
        benefits: ["Opción de alineadores transparentes", "Tecnología invisible", "Para todas las edades", "Mejora la salud oral", "Resultados permanentes", "Simulación digital"],
        steps: [
          { step: "1", title: "Examen Ortodóncico", desc: "Evaluación integral con modelo dental, radiografía y análisis fotográfico." },
          { step: "2", title: "Plan de Tratamiento", desc: "Plan personalizado y estimación de duración." },
          { step: "3", title: "Aplicación de Aparato", desc: "Sistema elegido (alineador transparente, metal o cerámica) colocado." },
          { step: "4", title: "Retención", desc: "Resultado permanente preservado con retenedor post-tratamiento." },
        ],
      },
    },
  },
  it: {
    nav: ["Home", "Chi Siamo", "Servizi", "Operazioni", "Contattaci"],
    freeConsult: "Consulenza Gratuita",
    heroBadge: "Istanbul, Turchia — Haliç Panorama Dental",
    heroTitle1: "Ottieni il tuo",
    heroTitleHighlight: "Sorriso dei Sogni",
    heroTitle2: "",
    heroDesc: "Riscopri la tua fiducia con il sorriso Hollywood, gli impianti dentali e i trattamenti estetici. Un'esperienza VIP dal trasferimento aeroportuale alla clinica.",
    heroCta: "Trattamenti Dentali",
    marquee: ["🦷 Sorriso Hollywood — Risultati Perfetti", "✨ Soluzioni Permanenti con Impianti Dentali", "💎 Specialisti in Corone in Zirconio", "🪥 Trattamenti Sbiancamento", "📞 Linea di Consulenza Gratuita 24/7"],
    sliderCategory: "Trattamenti Dentali",
    servicesLabel: "I Nostri Trattamenti",
    servicesTitle: "Servizi di Cura Dentale",
    servicesDesc: "Garantisci la tua salute orale e il tuo sorriso estetico con i nostri servizi dentali completi.",
    exploreBtn: "Scopri →",
    services: [
      { title: "Impianto Dentale", desc: "Soluzioni permanenti per denti mancanti con sistemi All-on-4 e All-on-6." },
      { title: "Sorriso Hollywood", desc: "Design del sorriso perfetto con faccette in porcellana e corone in zirconio." },
      { title: "Sbiancamento Dentale", desc: "Risultati professionali e veloci con sbiancamento laser." },
      { title: "Corona in Zirconio", desc: "Aspetto naturale con corone in zirconio estetiche e durature." },
      { title: "Innesto Osseo", desc: "Rigenerazione ossea e rialzo del seno per impianti dentali." },
      { title: "Ortodonzia", desc: "Allineamento dentale estetico con allineatori trasparenti e apparecchi fissi." },
    ],
    stats: ["Anni di Esperienza", "Impianti Riusciti", "Sorrisi Hollywood", "Soddisfazione Pazienti"],
    beforeAfterBadge: "Risultati Reali dei Pazienti",
    beforeAfterTitle: "Prima & Dopo",
    beforeAfterHighlight: "Trasformazioni",
    beforeAfterDesc: "Scopri le incredibili trasformazioni dei nostri veri pazienti trattati a Haliç Panorama Dental.",
    trustBar: ["Pazienti Felici", "Soddisfazione", "Anni Esperienza", "Paesi"],
    caseLabel: "Caso",
    ctaBadge: "Il Tuo Sorriso dei Sogni",
    ctaTitle: "Vivi anche tu questa trasformazione",
    ctaDesc: "Prenota la tua consulenza gratuita, i nostri esperti determineranno il trattamento più adatto per te.",
    ctaBtn: "Consulenza Gratuita",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "I Nostri Specialisti",
    doctorsTitle: "Incontra i Nostri Dentisti",
    doctorsDesc: "Scegli il tuo medico preferito e prenota un appuntamento in pochi minuti.",
    appointmentBtn: "Prenota Appuntamento",
    doctors: [
      { specialty: "Dentista Estetica & Specialista Implantologia", exp: "12 anni di esperienza" },
      { specialty: "Specialista Ortodonzia", exp: "8 anni di esperienza" },
      { specialty: "Specialista Parodontologia & Gengive", exp: "10 anni di esperienza" },
      { specialty: "Specialista Chirurgia Orale & Maxillofacciale", exp: "9 anni di esperienza" },
      { specialty: "Specialista Odontoiatria Restaurativa", exp: "7 anni di esperienza" },
      { specialty: "Specialista Endodonzia", exp: "11 anni di esperienza" },
      { specialty: "Specialista Odontoiatria Protesica", exp: "6 anni di esperienza" },
    ],
    whyLabel: "Perché Noi?",
    whyTitle: "Perché Scegliere Panorama Dental?",
    whyDesc: "Scegliere la clinica giusta per il trattamento dentale è una decisione che cambia la vita.",
    reasons: [
      { title: "Dentisti Esperti", desc: "I nostri dentisti certificati internazionalmente portano anni di esperienza ad ogni procedura." },
      { title: "Ultima Tecnologia", desc: "Eseguiamo i trattamenti più precisi con tomografia 3D e sistemi laser." },
      { title: "Ambiente Sterile e Sicuro", desc: "Offriamo l'ambiente più igienico con protocolli di sterilizzazione internazionali." },
      { title: "Trattamento Rapido e Confortevole", desc: "Grandi trasformazioni possibili in una singola sessione." },
    ],
    packagesLabel: "SERVIZI VIP",
    packagesTitle: "Abbiamo Pensato a Te",
    packages: [
      { title: "Trasferimento Aeroportuale", desc: "Goditi un trasferimento senza stress dall'aeroporto a Panorama Dental." },
      { title: "Alloggio in Hotel", desc: "Abbiamo partnership con hotel vicini che offrono varie opzioni." },
      { title: "Trasporto 24/7", desc: "I nostri servizi di trasporto sono disponibili 24 ore su 24." },
      { title: "Servizio Interprete", desc: "Abbiamo interpreti specializzati in tutte le lingue per la tua visita in Turchia." },
    ],
    deptLabel: "I Nostri Reparti",
    deptTitle: "Tutte le Aree di Trattamento Dentale",
    deptDesc: "Panorama Dental offre servizi completi in tutte le aree della salute orale e dentale.",
    departments: ["Impianto Dentale", "Sorriso Hollywood", "Corona in Zirconio", "Sbiancamento Dentale", "Faccetta in Porcellana", "Ortodonzia", "Endodonzia", "Cura delle Gengive", "Innesto Osseo", "All-on-4 / All-on-6", "Odontoiatria Pediatrica", "Igiene Orale"],
    contactLabel: "Contatto",
    contactTitle: "Consulenza Gratuita",
    contactDesc: "Non esitare a farci le tue domande. Compila il modulo, ti richiameremo.",
    phone: "Telefono", email: "Email", address: "Indirizzo",
    freeConsultLine: "Consulenza Gratuita 24/7",
    namePlaceholder: "Il Tuo Nome Completo",
    emailPlaceholder: "Il Tuo Indirizzo Email",
    phonePlaceholder: "Il Tuo Numero di Telefono",
    messagePlaceholder: "Il Tuo Messaggio...",
    sendBtn: "Invia",
    uploadTitle: "Carica Radiografia o Foto",
    uploadDesc: "JPG, PNG, PDF — Puoi selezionare più file",
    whatsappText: "Ciao, sono",
    treatmentAbout: "Sul Trattamento",
    treatmentBenefits: "Vantaggi",
    treatmentProcess: "Processo di Trattamento",
    treatmentCtaBadge: "Valutazione Gratuita",
    treatmentCtaDesc: "Lascia che il nostro team esperto ti valuti gratuitamente e crei il tuo piano di trattamento personale.",
    treatmentCtaBtn1: "Scrivi su WhatsApp",
    treatmentCtaBtn2: "Chiama Ora",
    backHome: "Torna alla Home",
    notFound: "Trattamento non trovato",
    treatments: {
      "dis-implanti": {
        title: "Impianto Dentale", subtitle: "Dental Implant", emoji: "🦷",
        description: "Un impianto dentale è la soluzione più permanente e dall'aspetto naturale per i denti mancanti. L'impianto di titanio a forma di vite viene inserito nell'osso mascellare per creare una base simile alla radice del dente naturale.",
        benefits: ["Aspetto e sensazione naturali", "Durata 20+ anni", "Nessun danno ai denti adiacenti", "Previene la perdita ossea", "Comfort nel mangiare e bere", "Aumento della fiducia"],
        steps: [
          { step: "1", title: "Esame e Pianificazione", desc: "Analisi orale completa con tomografia 3D e piano di trattamento personalizzato." },
          { step: "2", title: "Inserimento Impianto", desc: "Impianto di titanio inserito nell'osso mascellare sotto anestesia locale." },
          { step: "3", title: "Processo di Guarigione", desc: "Processo di osseointegrazione (fusione ossea) di 2-4 mesi." },
          { step: "4", title: "Sovrastruttura e Consegna", desc: "Sorriso perfetto completato con corona in zirconio o porcellana." },
        ],
      },
      "hollywood-gulusu": {
        title: "Sorriso Hollywood", subtitle: "Hollywood Smile", emoji: "✨",
        description: "Il Sorriso Hollywood è un trattamento estetico dentale completo che perfeziona forma, colore e posizione dei denti usando faccette in porcellana e corone in zirconio.",
        benefits: ["Trasformazione istantanea", "Aspetto naturale in porcellana", "Resistente alle macchie", "Minima limatura", "Durata 10-15 anni", "Esplosione di fiducia"],
        steps: [
          { step: "1", title: "Design Digitale del Sorriso", desc: "Simulazione personalizzata del sorriso al computer." },
          { step: "2", title: "Applicazione Mock-Up", desc: "Prova e approva il risultato con una faccetta temporanea." },
          { step: "3", title: "Incollaggio Laminati", desc: "Laminati in porcellana da 0.3-0.5 mm incollati ai denti." },
          { step: "4", title: "Ritocchi Finali", desc: "Controllo di colore, forma e morso. Il tuo sorriso da sogno viene consegnato." },
        ],
      },
      "dis-beyazlatma": {
        title: "Sbiancamento Dentale", subtitle: "Teeth Whitening", emoji: "🪥",
        description: "Schiarisci i tuoi denti fino a 8 tonalità con lo sbiancamento dentale professionale laser. Risultati rapidi e duraturi con gel sbiancante sicuro e attivazione LED/laser in ambiente clinico.",
        benefits: ["8 tonalità in 1 sessione", "Nessun danno allo smalto", "Risultato visibile immediatamente", "Effetto duraturo", "Procedura indolore", "Prodotti approvati FDA"],
        steps: [
          { step: "1", title: "Pulizia della Superficie", desc: "Preparazione con rimozione del tartaro e della placca." },
          { step: "2", title: "Protezione delle Gengive", desc: "Gengive protette con gel e barriera di luce." },
          { step: "3", title: "Gel Sbiancante e Laser", desc: "Gel di perossido applicato e attivato con laser." },
          { step: "4", title: "Fluoruro Protettivo", desc: "Fluoruro rinforzante applicato alla fine della sessione." },
        ],
      },
      "zirkonyum-kaplama": {
        title: "Corona in Zirconio", subtitle: "Zirconia Crown", emoji: "💎",
        description: "Le corone in zirconio sono le corone dentali più naturali con struttura completamente in ceramica senza sottostruttura metallica. Grazie alla trasmissione della luce sono indistinguibili dai denti naturali.",
        benefits: ["Senza metallo", "Aspetto naturale traslucido", "Nessun rischio allergico", "Alta resistenza alle fratture", "Durata 15+ anni", "Corrispondenza perfetta del colore"],
        steps: [
          { step: "1", title: "Preparazione del Dente", desc: "Infrastruttura perfetta con taglio minimo del dente." },
          { step: "2", title: "Impronta e Design", desc: "Impronta orale digitale, design con sistema CAD/CAM." },
          { step: "3", title: "Corona Temporanea", desc: "Corona estetica temporanea durante il processo di laboratorio." },
          { step: "4", title: "Incollaggio Permanente", desc: "Corone in zirconio incollate permanentemente con adesivo di precisione." },
        ],
      },
      "kemik-grefti": {
        title: "Innesto Osseo", subtitle: "Bone Graft", emoji: "🦴",
        description: "L'innesto osseo è una procedura chirurgica che ripristina il volume osseo prima dell'applicazione dell'impianto in pazienti con perdita ossea.",
        benefits: ["Prepara il terreno per l'impianto", "Ferma la perdita ossea", "Preserva i contorni facciali", "Tasso di successo 95%+", "Tecniche minimamente invasive", "Opzione di sollevamento del seno"],
        steps: [
          { step: "1", title: "Analisi Ossea", desc: "Densità e volume osseo misurati con tomografia 3D CBCT." },
          { step: "2", title: "Selezione del Materiale", desc: "Materiale autologo, alloinnesto o sintetico pianificato." },
          { step: "3", title: "Applicazione Chirurgica", desc: "Innesto osseo posizionato sotto anestesia locale." },
          { step: "4", title: "Guarigione e Impianto", desc: "Applicazione impianto dopo 3-6 mesi di guarigione." },
        ],
      },
      "dis-teli-ortodonti": {
        title: "Ortodonzia", subtitle: "Orthodontics", emoji: "😁",
        description: "Correggi denti storti, affollati o spaziati con trattamenti ortodontici moderni. Soluzioni adatte a tutte le età.",
        benefits: ["Opzione allineatori trasparenti", "Tecnologia filo invisibile", "Adatto a tutte le età", "Migliora la salute orale", "Risultati permanenti", "Simulazione digitale"],
        steps: [
          { step: "1", title: "Esame Ortodontico", desc: "Valutazione completa con modello dentale, radiografia e analisi fotografica." },
          { step: "2", title: "Piano di Trattamento", desc: "Piano personalizzato e stima della durata." },
          { step: "3", title: "Applicazione dell'Apparecchio", desc: "Sistema scelto (allineatore trasparente, metallo o ceramica) applicato." },
          { step: "4", title: "Ritenzione", desc: "Risultato permanente preservato con ritenzione post-trattamento." },
        ],
      },
    },
  },
  fr: {
    nav: ["Accueil", "À Propos", "Services", "Opérations", "Contactez-Nous"],
    freeConsult: "Consultation Gratuite",
    heroBadge: "Istanbul, Turquie — Haliç Panorama Dental",
    heroTitle1: "Obtenez votre",
    heroTitleHighlight: "Sourire de Rêve",
    heroTitle2: "",
    heroDesc: "Retrouvez confiance en vous avec le sourire Hollywood, les implants dentaires et les traitements cosmétiques. Une expérience VIP du transfert aéroport à la clinique.",
    heroCta: "Traitements Dentaires",
    marquee: ["🦷 Sourire Hollywood — Résultats Parfaits", "✨ Solutions Permanentes avec Implants Dentaires", "💎 Spécialistes Couronnes Zircone", "🪥 Traitements Blanchiment", "📞 Ligne Consultation Gratuite 24/7"],
    sliderCategory: "Traitements Dentaires",
    servicesLabel: "Nos Traitements",
    servicesTitle: "Services de Soins Dentaires",
    servicesDesc: "Assurez votre santé bucco-dentaire et votre sourire esthétique avec nos services dentaires complets.",
    exploreBtn: "Explorer →",
    services: [
      { title: "Implant Dentaire", desc: "Solutions permanentes pour les dents manquantes avec les systèmes All-on-4 et All-on-6." },
      { title: "Sourire Hollywood", desc: "Design parfait du sourire avec des facettes en porcelaine et des couronnes en zircone." },
      { title: "Blanchiment Dentaire", desc: "Résultats professionnels et rapides avec le blanchiment au laser." },
      { title: "Couronne en Zircone", desc: "Aspect naturel avec des couronnes en zircone esthétiques et durables." },
      { title: "Greffe Osseuse", desc: "Régénération osseuse et élévation du sinus pour les implants dentaires." },
      { title: "Orthodontie", desc: "Alignement dentaire esthétique avec des aligneurs transparents et des appareils." },
    ],
    stats: ["Années d'Expérience", "Implants Réussis", "Sourires Hollywood", "Satisfaction Patients"],
    beforeAfterBadge: "Vrais Résultats de Patients",
    beforeAfterTitle: "Avant & Après",
    beforeAfterHighlight: "Transformations",
    beforeAfterDesc: "Découvrez les incroyables transformations de nos vrais patients traités à Haliç Panorama Dental.",
    trustBar: ["Patients Heureux", "Satisfaction", "Ans d'Expérience", "Pays"],
    caseLabel: "Cas",
    ctaBadge: "Votre Sourire de Rêve",
    ctaTitle: "Vivez vous aussi cette transformation",
    ctaDesc: "Réservez votre consultation gratuite, nos experts détermineront le traitement le plus adapté pour vous.",
    ctaBtn: "Consultation Gratuite",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Nos Spécialistes",
    doctorsTitle: "Rencontrez Nos Dentistes",
    doctorsDesc: "Choisissez votre médecin préféré et obtenez un rendez-vous en quelques minutes.",
    appointmentBtn: "Prendre Rendez-vous",
    doctors: [
      { specialty: "Dentiste Esthétique & Spécialiste Implantologie", exp: "12 ans d'expérience" },
      { specialty: "Spécialiste Orthodontie", exp: "8 ans d'expérience" },
      { specialty: "Spécialiste Parodontologie & Gencives", exp: "10 ans d'expérience" },
      { specialty: "Spécialiste Chirurgie Orale & Maxillo-Faciale", exp: "9 ans d'expérience" },
      { specialty: "Spécialiste Dentisterie Restauratrice", exp: "7 ans d'expérience" },
      { specialty: "Spécialiste Endodontie", exp: "11 ans d'expérience" },
      { specialty: "Spécialiste Dentisterie Prothétique", exp: "6 ans d'expérience" },
    ],
    whyLabel: "Pourquoi Nous?",
    whyTitle: "Pourquoi Choisir Panorama Dental?",
    whyDesc: "Choisir la bonne clinique pour votre traitement dentaire est une décision qui change la vie.",
    reasons: [
      { title: "Dentistes Experts", desc: "Nos dentistes certifiés internationalement apportent des années d'expérience à chaque procédure." },
      { title: "Dernière Technologie", desc: "Nous effectuons les traitements les plus précis avec tomographie 3D et systèmes laser." },
      { title: "Environnement Stérile et Sûr", desc: "Nous offrons l'environnement le plus hygiénique avec des protocoles de stérilisation internationaux." },
      { title: "Traitement Rapide et Confortable", desc: "Grandes transformations possibles en une seule séance." },
    ],
    packagesLabel: "SERVICES VIP",
    packagesTitle: "Nous Avons Pensé à Vous",
    packages: [
      { title: "Transfert Aéroport", desc: "Profitez d'un transfert sans stress de l'aéroport à Panorama Dental." },
      { title: "Hébergement à l'Hôtel", desc: "Nous avons des partenariats avec des hôtels proches offrant diverses options." },
      { title: "Transport 24/7", desc: "Nos services de transport sont disponibles 24 heures sur 24." },
      { title: "Service d'Interprète", desc: "Nous avons des interprètes spécialisés dans toutes les langues pour votre visite en Turquie." },
    ],
    deptLabel: "Nos Départements",
    deptTitle: "Tous les Domaines de Traitement Dentaire",
    deptDesc: "Panorama Dental offre des services complets dans tous les domaines de la santé bucco-dentaire.",
    departments: ["Implant Dentaire", "Sourire Hollywood", "Couronne en Zircone", "Blanchiment Dentaire", "Facette en Porcelaine", "Orthodontie", "Endodontie", "Traitement des Gencives", "Greffe Osseuse", "All-on-4 / All-on-6", "Dentisterie Pédiatrique", "Hygiène Bucco-Dentaire"],
    contactLabel: "Contact",
    contactTitle: "Consultation Gratuite",
    contactDesc: "N'hésitez pas à nous poser vos questions. Remplissez le formulaire, nous vous rappellerons.",
    phone: "Téléphone", email: "E-mail", address: "Adresse",
    freeConsultLine: "Consultation Gratuite 24/7",
    namePlaceholder: "Votre Nom Complet",
    emailPlaceholder: "Votre Adresse E-mail",
    phonePlaceholder: "Votre Numéro de Téléphone",
    messagePlaceholder: "Votre Message...",
    sendBtn: "Envoyer",
    uploadTitle: "Télécharger une Radiographie ou Photo",
    uploadDesc: "JPG, PNG, PDF — Vous pouvez sélectionner plusieurs fichiers",
    whatsappText: "Bonjour, je suis",
    treatmentAbout: "À Propos du Traitement",
    treatmentBenefits: "Avantages",
    treatmentProcess: "Processus de Traitement",
    treatmentCtaBadge: "Évaluation Gratuite",
    treatmentCtaDesc: "Laissez notre équipe d'experts vous évaluer gratuitement et créer votre plan de traitement personnel.",
    treatmentCtaBtn1: "Écrire sur WhatsApp",
    treatmentCtaBtn2: "Appeler Maintenant",
    backHome: "Retour à l'Accueil",
    notFound: "Traitement introuvable",
    treatments: {
      "dis-implanti": {
        title: "Implant Dentaire", subtitle: "Dental Implant", emoji: "🦷",
        description: "Un implant dentaire est la solution la plus permanente et la plus naturelle pour les dents manquantes. L'implant en titane est placé dans l'os maxillaire pour créer une base similaire à la racine dentaire naturelle.",
        benefits: ["Aspect et sensation naturels", "Durabilité 20+ ans", "Sans dommage aux dents adjacentes", "Prévient la perte osseuse", "Confort alimentaire", "Boost de confiance"],
        steps: [
          { step: "1", title: "Examen et Planification", desc: "Analyse buccale complète avec tomographie 3D et plan de traitement personnalisé." },
          { step: "2", title: "Pose de l'Implant", desc: "Implant en titane posé dans la mâchoire sous anesthésie locale." },
          { step: "3", title: "Processus de Guérison", desc: "Processus d'ostéo-intégration (fusion osseuse) de 2-4 mois." },
          { step: "4", title: "Superstructure et Livraison", desc: "Sourire parfait complété par une couronne en zircone ou porcelaine." },
        ],
      },
      "hollywood-gulusu": {
        title: "Sourire Hollywood", subtitle: "Hollywood Smile", emoji: "✨",
        description: "Le Sourire Hollywood est un traitement dentaire esthétique complet qui perfectionne la forme, la couleur et la position des dents grâce aux facettes en porcelaine et couronnes en zircone.",
        benefits: ["Transformation instantanée", "Aspect naturel en porcelaine", "Résistant aux taches", "Meulage minimal", "Durée de vie 10-15 ans", "Explosion de confiance"],
        steps: [
          { step: "1", title: "Conception Numérique du Sourire", desc: "Simulation personnalisée du sourire sur ordinateur." },
          { step: "2", title: "Application Mock-Up", desc: "Essayez et approuvez le résultat avec une facette temporaire." },
          { step: "3", title: "Collage des Facettes", desc: "Facettes en porcelaine de 0.3-0.5 mm collées sur les dents." },
          { step: "4", title: "Retouches Finales", desc: "Contrôle couleur, forme et occlusion. Votre sourire de rêve est livré." },
        ],
      },
      "dis-beyazlatma": {
        title: "Blanchiment Dentaire", subtitle: "Teeth Whitening", emoji: "🪥",
        description: "Éclaircissez vos dents jusqu'à 8 teintes avec le blanchiment dentaire professionnel au laser. Résultats rapides et durables avec gel sûr et activation LED/laser en milieu clinique.",
        benefits: ["8 teintes en 1 séance", "Pas de dommage à l'émail", "Résultat visible immédiatement", "Effet durable", "Procédure indolore", "Produits approuvés FDA"],
        steps: [
          { step: "1", title: "Nettoyage de Surface", desc: "Préparation avec élimination du tartre et de la plaque." },
          { step: "2", title: "Protection Gingivale", desc: "Gencives protégées avec gel et barrière lumineuse." },
          { step: "3", title: "Gel et Laser", desc: "Gel de peroxyde appliqué et activé avec laser." },
          { step: "4", title: "Fluor Protecteur", desc: "Fluor renforçant appliqué en fin de séance." },
        ],
      },
      "zirkonyum-kaplama": {
        title: "Couronne en Zircone", subtitle: "Zirconia Crown", emoji: "💎",
        description: "Les couronnes en zircone sont les couronnes les plus naturelles avec une structure tout céramique sans infrastructure métallique. Grâce à la transmission de lumière, elles sont indiscernables des dents naturelles.",
        benefits: ["Sans métal", "Aspect naturel translucide", "Aucun risque allergique", "Haute résistance aux fractures", "Durée de vie 15+ ans", "Correspondance couleur parfaite"],
        steps: [
          { step: "1", title: "Préparation Dentaire", desc: "Infrastructure parfaite avec coupe dentaire minimale." },
          { step: "2", title: "Empreinte et Design", desc: "Empreinte buccale numérique, design avec système CAD/CAM." },
          { step: "3", title: "Couronne Temporaire", desc: "Couronne esthétique temporaire pendant le processus de laboratoire." },
          { step: "4", title: "Collage Permanent", desc: "Couronnes en zircone collées définitivement avec adhésif de précision." },
        ],
      },
      "kemik-grefti": {
        title: "Greffe Osseuse", subtitle: "Bone Graft", emoji: "🦴",
        description: "La greffe osseuse est une procédure chirurgicale qui restaure le volume osseux avant l'application d'implants chez les patients souffrant de perte osseuse.",
        benefits: ["Prépare le terrain pour l'implant", "Arrête la perte osseuse", "Préserve les contours du visage", "Taux de réussite 95%+", "Techniques peu invasives", "Option d'élévation du sinus"],
        steps: [
          { step: "1", title: "Analyse Osseuse", desc: "Densité et volume osseux mesurés par tomographie CBCT 3D." },
          { step: "2", title: "Sélection du Matériau", desc: "Matériau autologue, allogreffe ou synthétique planifié." },
          { step: "3", title: "Application Chirurgicale", desc: "Greffe osseuse placée sous anesthésie locale." },
          { step: "4", title: "Guérison et Implant", desc: "Application de l'implant après 3-6 mois de guérison." },
        ],
      },
      "dis-teli-ortodonti": {
        title: "Orthodontie", subtitle: "Orthodontics", emoji: "😁",
        description: "Corrigez les dents tordues, serrées ou espacées avec des traitements orthodontiques modernes. Solutions adaptées à tous les âges.",
        benefits: ["Option aligneurs transparents", "Technologie fil invisible", "Adapté à tous les âges", "Améliore la santé buccale", "Résultats permanents", "Simulation numérique"],
        steps: [
          { step: "1", title: "Examen Orthodontique", desc: "Évaluation complète avec modèle dentaire, radiographie et analyse photographique." },
          { step: "2", title: "Plan de Traitement", desc: "Plan personnalisé et estimation de la durée." },
          { step: "3", title: "Application de l'Appareil", desc: "Système choisi (aligneur transparent, métal ou céramique) mis en place." },
          { step: "4", title: "Rétention", desc: "Résultat permanent préservé avec contention post-traitement." },
        ],
      },
    },
  },
  ru: {
    nav: ["Главная", "О Нас", "Услуги", "Операции", "Свяжитесь с Нами"],
    freeConsult: "Бесплатная Консультация",
    heroBadge: "Стамбул, Турция — Haliç Panorama Dental",
    heroTitle1: "Получите улыбку",
    heroTitleHighlight: "Вашей Мечты",
    heroTitle2: "",
    heroDesc: "Обретите уверенность с голливудской улыбкой, зубными имплантами и косметическими процедурами. VIP-опыт от трансфера из аэропорта до клиники.",
    heroCta: "Стоматологические Услуги",
    marquee: ["🦷 Голливудская Улыбка — Идеальные Результаты", "✨ Постоянные Решения с Зубными Имплантами", "💎 Специалисты по Циркониевым Коронкам", "🪥 Процедуры Отбеливания Зубов", "📞 Бесплатная Консультация 24/7"],
    sliderCategory: "Стоматологические Услуги",
    servicesLabel: "Наши Услуги",
    servicesTitle: "Стоматологические Услуги",
    servicesDesc: "Обеспечьте здоровье полости рта и эстетическую улыбку с нашими комплексными стоматологическими услугами.",
    exploreBtn: "Подробнее →",
    services: [
      { title: "Зубной Имплант", desc: "Постоянные решения для отсутствующих зубов с системами All-on-4 и All-on-6." },
      { title: "Голливудская Улыбка", desc: "Идеальный дизайн улыбки с фарфоровыми винирами и циркониевыми коронками." },
      { title: "Отбеливание Зубов", desc: "Профессиональные и быстрые результаты с лазерным отбеливанием." },
      { title: "Циркониевая Коронка", desc: "Естественный вид с эстетичными и прочными циркониевыми коронками." },
      { title: "Костная Пластика", desc: "Регенерация кости и синус-лифтинг для зубных имплантов." },
      { title: "Ортодонтия", desc: "Эстетическое выравнивание зубов с прозрачными элайнерами и брекетами." },
    ],
    stats: ["Лет Опыта", "Успешных Имплантов", "Голливудских Улыбок", "Удовлетворённость Пациентов"],
    beforeAfterBadge: "Реальные Результаты Пациентов",
    beforeAfterTitle: "До & После",
    beforeAfterHighlight: "Трансформации",
    beforeAfterDesc: "Откройте для себя невероятные преобразования наших реальных пациентов в Haliç Panorama Dental.",
    trustBar: ["Довольных Пациентов", "Удовлетворённость", "Лет Опыта", "Стран"],
    caseLabel: "Случай",
    ctaBadge: "Улыбка Вашей Мечты",
    ctaTitle: "Переживите и вы это преображение",
    ctaDesc: "Запишитесь на бесплатную консультацию, наши специалисты определят наиболее подходящее лечение для вас.",
    ctaBtn: "Бесплатная Консультация",
    whatsappBtn: "WhatsApp",
    doctorsLabel: "Наши Специалисты",
    doctorsTitle: "Познакомьтесь с Нашими Стоматологами",
    doctorsDesc: "Выберите предпочтительного врача и запишитесь на приём за несколько минут.",
    appointmentBtn: "Записаться",
    doctors: [
      { specialty: "Эстетический Стоматолог & Специалист по Имплантологии", exp: "12 лет опыта" },
      { specialty: "Специалист по Ортодонтии", exp: "8 лет опыта" },
      { specialty: "Специалист по Пародонтологии & Дёснам", exp: "10 лет опыта" },
      { specialty: "Специалист по Челюстно-Лицевой Хирургии", exp: "9 лет опыта" },
      { specialty: "Специалист по Реставрационной Стоматологии", exp: "7 лет опыта" },
      { specialty: "Специалист по Эндодонтии", exp: "11 лет опыта" },
      { specialty: "Специалист по Протезированию", exp: "6 лет опыта" },
    ],
    whyLabel: "Почему Мы?",
    whyTitle: "Почему Выбирают Panorama Dental?",
    whyDesc: "Выбор правильной клиники для лечения зубов — это решение, меняющее жизнь.",
    reasons: [
      { title: "Опытные Стоматологи", desc: "Наши международно сертифицированные стоматологи привносят многолетний опыт в каждую процедуру." },
      { title: "Новейшие Технологии", desc: "Мы выполняем точнейшие процедуры с 3D-томографией и лазерными системами." },
      { title: "Стерильная и Безопасная Среда", desc: "Мы обеспечиваем максимально гигиеничную среду с международными протоколами стерилизации." },
      { title: "Быстрое и Комфортное Лечение", desc: "Большие преобразования возможны за один сеанс." },
    ],
    packagesLabel: "VIP УСЛУГИ",
    packagesTitle: "Мы Позаботились о Вас",
    packages: [
      { title: "Трансфер из Аэропорта", desc: "Наслаждайтесь трансфером без стресса от аэропорта до Panorama Dental." },
      { title: "Проживание в Отеле", desc: "У нас есть партнёрства с близлежащими отелями, предлагающими различные варианты." },
      { title: "Транспорт 24/7", desc: "Наши транспортные услуги доступны круглосуточно." },
      { title: "Услуги Переводчика", desc: "У нас есть специализированные переводчики на все языки для вашего визита в Турцию." },
    ],
    deptLabel: "Наши Отделения",
    deptTitle: "Все Области Стоматологического Лечения",
    deptDesc: "Panorama Dental предоставляет комплексные услуги во всех областях здоровья полости рта.",
    departments: ["Зубной Имплант", "Голливудская Улыбка", "Циркониевая Коронка", "Отбеливание Зубов", "Фарфоровый Винир", "Ортодонтия", "Эндодонтия", "Лечение Дёсен", "Костная Пластика", "All-on-4 / All-on-6", "Детская Стоматология", "Гигиена Полости Рта"],
    contactLabel: "Контакты",
    contactTitle: "Бесплатная Консультация",
    contactDesc: "Не стесняйтесь задавать нам вопросы. Заполните форму, мы перезвоним вам.",
    phone: "Телефон", email: "Электронная Почта", address: "Адрес",
    freeConsultLine: "Бесплатная Консультация 24/7",
    namePlaceholder: "Ваше Полное Имя",
    emailPlaceholder: "Ваш Адрес Электронной Почты",
    phonePlaceholder: "Ваш Номер Телефона",
    messagePlaceholder: "Ваше Сообщение...",
    sendBtn: "Отправить",
    uploadTitle: "Загрузить рентген или фото",
    uploadDesc: "JPG, PNG, PDF — Вы можете выбрать несколько файлов",
    whatsappText: "Здравствуйте, я",
    treatmentAbout: "О Лечении",
    treatmentBenefits: "Преимущества",
    treatmentProcess: "Процесс Лечения",
    treatmentCtaBadge: "Бесплатная Оценка",
    treatmentCtaDesc: "Пусть наша команда экспертов бесплатно оценит вас и составит личный план лечения.",
    treatmentCtaBtn1: "Написать в WhatsApp",
    treatmentCtaBtn2: "Позвонить",
    backHome: "Вернуться на Главную",
    notFound: "Лечение не найдено",
    treatments: {
      "dis-implanti": {
        title: "Зубной Имплант", subtitle: "Dental Implant", emoji: "🦷",
        description: "Зубной имплант — это самое долговечное и естественно выглядящее решение для потерянных зубов. Имплант из титана вкручивается в челюстную кость, создавая основу, похожую на корень натурального зуба.",
        benefits: ["Естественный вид и ощущение", "Долговечность 20+ лет", "Не вредит соседним зубам", "Предотвращает потерю кости", "Комфорт при еде и питье", "Повышение уверенности"],
        steps: [
          { step: "1", title: "Осмотр и планирование", desc: "Комплексный анализ полости рта с 3D томографией и персональный план лечения." },
          { step: "2", title: "Установка импланта", desc: "Титановый имплант устанавливается в челюсть под местной анестезией." },
          { step: "3", title: "Процесс заживления", desc: "2–4 месяца остеоинтеграции (сращения с костью)." },
          { step: "4", title: "Надстройка и сдача", desc: "Идеальная улыбка завершается циркониевой или фарфоровой коронкой." },
        ],
      },
      "hollywood-gulusu": {
        title: "Голливудская Улыбка", subtitle: "Hollywood Smile", emoji: "✨",
        description: "Голливудская Улыбка — комплексное эстетическое стоматологическое лечение, которое совершенствует форму, цвет и положение зубов с помощью фарфоровых виниров и циркониевых коронок.",
        benefits: ["Мгновенное преображение", "Натуральный фарфоровый вид", "Устойчивость к пятнам", "Минимальная обточка", "Срок службы 10-15 лет", "Взрыв уверенности"],
        steps: [
          { step: "1", title: "Цифровой дизайн улыбки", desc: "Персонализированная симуляция улыбки на компьютере." },
          { step: "2", title: "Применение Mock-Up", desc: "Попробуйте и утвердите результат с временным виниром." },
          { step: "3", title: "Приклеивание ламинатов", desc: "Фарфоровые ламинаты толщиной 0.3-0.5 мм приклеиваются к зубам." },
          { step: "4", title: "Финальные штрихи", desc: "Контроль цвета, формы и прикуса. Улыбка вашей мечты сдаётся." },
        ],
      },
      "dis-beyazlatma": {
        title: "Отбеливание Зубов", subtitle: "Teeth Whitening", emoji: "🪥",
        description: "Осветлите зубы до 8 тонов с профессиональным лазерным отбеливанием. Быстрые и долговечные результаты с безопасным гелем и активацией LED/лазером в клинических условиях.",
        benefits: ["8 тонов за 1 сеанс", "Без вреда для эмали", "Мгновенный видимый результат", "Долгосрочный эффект", "Безболезненная процедура", "Одобренные FDA продукты"],
        steps: [
          { step: "1", title: "Очистка поверхности зубов", desc: "Подготовка с удалением зубного камня и налёта." },
          { step: "2", title: "Защита дёсен", desc: "Дёсны защищены гелем и световым барьером." },
          { step: "3", title: "Гель и лазер", desc: "Активный гель перекиси нанесён и активирован лазером." },
          { step: "4", title: "Защитный фтор", desc: "Укрепляющий фтор нанесён в конце сеанса." },
        ],
      },
      "zirkonyum-kaplama": {
        title: "Циркониевая Коронка", subtitle: "Zirconia Crown", emoji: "💎",
        description: "Циркониевые коронки — самые натуральные зубные коронки с полностью керамической структурой без металлической подосновы. Благодаря светопропусканию их невозможно отличить от натуральных зубов.",
        benefits: ["Без металла", "Светопроводящий натуральный вид", "Нулевой риск аллергии", "Высокая прочность на излом", "Срок службы 15+ лет", "Идеальное совпадение цвета"],
        steps: [
          { step: "1", title: "Подготовка зуба", desc: "Идеальная инфраструктура с минимальным обпиливанием зуба." },
          { step: "2", title: "Слепок и дизайн", desc: "Цифровой слепок полости рта, дизайн с системой CAD/CAM." },
          { step: "3", title: "Временная коронка", desc: "Временная эстетическая коронка в процессе лабораторной работы." },
          { step: "4", title: "Постоянная фиксация", desc: "Циркониевые коронки постоянно зафиксированы прецизионным адгезивом." },
        ],
      },
      "kemik-grefti": {
        title: "Костная Пластика", subtitle: "Bone Graft", emoji: "🦴",
        description: "Костная пластика — хирургическая процедура, которая восстанавливает объём кости перед установкой импланта у пациентов с потерей костной ткани.",
        benefits: ["Готовит почву для импланта", "Останавливает потерю кости", "Сохраняет контуры лица", "Успех 95%+", "Малоинвазивные техники", "Вариант синус-лифтинга"],
        steps: [
          { step: "1", title: "Анализ кости", desc: "Плотность и объём кости измеряются с 3D CBCT томографией." },
          { step: "2", title: "Выбор материала", desc: "Планируется аутологичный, аллогенный или синтетический материал." },
          { step: "3", title: "Хирургическое применение", desc: "Костный трансплантат устанавливается под местной анестезией." },
          { step: "4", title: "Заживление и имплант", desc: "Установка импланта после 3–6 месяцев заживления." },
        ],
      },
      "dis-teli-ortodonti": {
        title: "Ортодонтия", subtitle: "Orthodontics", emoji: "😁",
        description: "Исправьте кривые, скученные или расставленные зубы с помощью современных ортодонтических методов. Решения для всех возрастов.",
        benefits: ["Вариант прозрачных элайнеров", "Технология невидимой дуги", "Подходит для всех возрастов", "Улучшает здоровье полости рта", "Постоянные результаты", "Цифровая симуляция"],
        steps: [
          { step: "1", title: "Ортодонтический осмотр", desc: "Комплексная оценка с моделью зубов, рентгеном и фото анализом." },
          { step: "2", title: "План лечения", desc: "Персонализированный план и оценка продолжительности." },
          { step: "3", title: "Установка аппарата", desc: "Выбранная система (прозрачный элайнер, металл или керамика) установлена." },
          { step: "4", title: "Ретенция", desc: "Постоянный результат сохраняется ретейнером после лечения." },
        ],
      },
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "tr");

  const handleSetLang = (newLang) => {
    localStorage.setItem("lang", newLang);
    setLang(newLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}